-- Generated by tools/build_skin_index.py from assets/skins/catalog.json. Do not edit.
-- Display data for each skin collection, keyed by main/data/skins.lua's `collection`.

local M = {}

M.COLLECTIONS = {
	["aurora"] = { name = "Aurora", kind = "recolor", description = "Deep teal enamel, mint armor and glacial blue trim." },
	["solar_regatta"] = { name = "Solar Regatta", kind = "recolor", description = "Crimson racing panels, warm ivory armor and amber details." },
	["royal_amethyst"] = { name = "Royal Amethyst", kind = "recolor", description = "Plum enamel, lavender armor and champagne-gold trim." },
	["clockwork"] = { name = "Clockwork", kind = "model", description = "Brass and copper machinery, verdigris enamel and canvas-colored fins." },
	["porcelain_dynasty"] = { name = "Porcelain Dynasty", kind = "surface", description = "Ivory ceramic, cobalt botanical scrollwork and fine gold repair seams." },
	["starlight"] = { name = "Starlight", kind = "surface", description = "Midnight enamel, authored constellations, silver edging and scattered starlight." },
	["grand_prix"] = { name = "Grand Prix", kind = "surface", description = "Navy racing panels, ivory stripes, orange accents, checkerboards and individual hull numbers." },
	["abyssal"] = { name = "Abyssal", kind = "model", description = "Deep-ocean armor, pearl lenses, bright photophore chains and delicate sensory tendrils." },
	["crystalborn"] = { name = "Crystalborn", kind = "model", description = "Faceted amethyst armor, mint-quartz growths and angular crystal crownlets." },
	["corsair"] = { name = "Corsair", kind = "model", description = "Timber plating, canvas fin panels, braided rigging, portholes and broadside cannon housings." },
	["overgrown"] = { name = "Overgrown", kind = "model", description = "Living armor: coral and barnacles on fish, climbing vines and blossoms on birds." },
	["toybox"] = { name = "Toybox", kind = "model", description = "Painted tin animals with candy-colored panels, chunky fasteners, decorative axles and a wind-up key." },
}

return M
