-- GENERATED by tools/sync_server_rules.py from main/data/ranks.lua - edit that file, not this copy.
-- Levels and ranks (plan.md §2.2): a player's level comes from their total
-- XP on a game server, and each faction has its own rank name per level.
--
-- The curve is BSGO's (bsgo.fandom.com/wiki/In-game_ranks): level n needs
-- 1,000 x (n - 1)^2 total XP - 1,000 for level 2, 4,000 for 3, 81,000 for
-- 10, 361,000 for 20. Ranks are named for levels 1-20; levels carry on
-- past 20 and keep the level-20 rank, as in BSGO.
--
-- The rank names are Galaxy's own (BSGO's are BSG's): the Accord's are naval
-- (its ships are fish), the Swarm's are drawn from flocks and birds of prey
-- (its ships are birds). DRAFT names, per direct instruction - edit freely.
-- Shared by the game and the server (tools/sync_server_rules.py).

local M = {}

M.XP_PER_LEVEL_STEP = 1000

M.RANKS = {
	accord = {
		"Cadet", "Deckhand", "Able Spacer", "Coxswain", "Petty Officer",
		"Chief Petty Officer", "Midshipman", "Sub-Lieutenant", "Lieutenant", "Senior Lieutenant",
		"Lieutenant Commander", "Commander", "Senior Commander", "Captain", "Senior Captain",
		"Commodore", "Rear Admiral", "Vice Admiral", "Admiral", "Fleet Admiral",
	},
	swarm = {
		"Hatchling", "Nestling", "Fledgling", "Flitter", "Glider",
		"Swift", "Wingmate", "Flight Leader", "Talon", "Senior Talon",
		"Hawk", "Senior Hawk", "Falcon", "Senior Falcon", "Eagle",
		"Storm Eagle", "Flock Warden", "Flock Marshal", "Sky Sovereign", "Apex",
	},
}

-- Total XP needed to reach `level` (1 needs 0).
function M.xp_for_level(level)
	return M.XP_PER_LEVEL_STEP * (level - 1) * (level - 1)
end

-- The level reached with `xp` total XP.
function M.level_for_xp(xp)
	local level = math.floor(math.sqrt(math.max(0, xp or 0) / M.XP_PER_LEVEL_STEP)) + 1
	-- guard against floating-point edges right at a boundary
	while M.xp_for_level(level + 1) <= (xp or 0) do
		level = level + 1
	end
	while level > 1 and M.xp_for_level(level) > (xp or 0) do
		level = level - 1
	end
	return level
end

-- `faction`'s rank name at `level` (the level-20 rank beyond 20).
function M.rank_name(faction, level)
	local names = M.RANKS[faction]
	if not names then
		return nil
	end
	return names[math.min(math.max(level or 1, 1), #names)]
end

return M
