-- GENERATED by tools/sync_server_rules.py from main/data/ships.lua - edit that file, not this copy.
-- The ship roster - individual named ships within each class (plan.md §2.1).
-- Distinct from the class-level baseline stats every ship inherits (§2.1.1).
--
-- STRUCTURE (plan.md §2.1.3, per direct instruction): because most ships can
-- be upgraded to an ADVANCED tier, a ship entry's own properties are split
-- into two sections, `basic` and `advanced`. Everything a ship has lives in
-- one of those two, EXCEPT the fields shared by both tiers, which stay at the
-- top level of the entry:
--   * `class`        - the size tier (Patrol/Escort/Frigate/Carrier)
--   * `role`         - the Interceptor/Support/Assault/Tactical role
--   * `slot_positions` - ONE list of every slot on the hull, shared by both
--                        tiers; each entry's own `tier` field says whether
--                        that slot exists on the basic hull or is only
--                        unlocked once advanced
--   * `flight_camera`, `faction_skins`
-- Each tier section holds `price`, `data` and `components`:
--   * `price`     - an ORDERED LIST of `{ amount, currency }` entries, one
--                   per currency the purchase demands, so a ship can require
--                   MORE THAN ONE currency at once (direct instruction: a
--                   ship that "requires multiple currencies to purchase
--                   it"). A one-currency price is the common case
--                   (`{ { amount = 36000, currency = "tope" } }`); a two-
--                   currency price is simply two entries:
--                     price = {
--                       { amount = 36000, currency = "tope" },
--                       { amount = 500,   currency = "hydrogen" },
--                     }
--                   Every entry must be payable at once - payment is
--                   ALL-OR-NOTHING, never part-paid (session.can_afford /
--                   session.spend_price) - and the outpost joins the
--                   entries for display ("36,000 Tope + 500 Hydrogen").
--                   `currency` is one of "tope", "hydrogen" or "valour"
--                   (plan.md §2.6's three spendable balances; Valour is the
--                   PvP currency). `nil` = not for sale (the starter ship).
--   * `basic`     - the ship as bought/owned/fitted before any upgrade
--   * `advanced`  - present ONLY for a ship that HAS an advanced tier; a ship
--                   without one simply omits the whole `advanced` key (nil -
--                   the existing `if ship.advanced` truthiness tests already
--                   treat that as "no upgrade offered")
-- An `advanced` section only lists the fields that actually CHANGE; anything
-- it leaves unset falls back to `basic` (session.ship_stat/get_ship_data,
-- outpost.gui_script's effective_components). `advanced.price` is the UPGRADE
-- price, charged on top of whatever the basic ship already cost - no refund
-- of that basic price (direct instruction) - and has the same
-- ordered-list-of-currencies shape as `basic.price` above.
--
-- SOURCE OF TRUTH (per direct instruction): the PATROL-class ships
-- (`patrol_interceptor`, `patrol_support`, `patrol_assault`,
-- `patrol_tactical`) take every stat, slot count and price from
-- `revised-patrol-ships.csv` in the project root (documented in plan.md
-- §2.1.4), which supersedes the earlier §2.13 figures and placeholders for
-- those four. The Escort/Frigate entries below still carry their own
-- previously-sourced numbers unchanged.
--
-- Per-faction differences are deliberately narrow: only `name`, `model`,
-- and `weapon_gui` vary between The Accord's and The Swarm's version of a
-- given ship - every stat/characteristic is shared. That's stored as one
-- entry with a small `faction_skins` override table, NOT two separate
-- per-faction listings - duplicating a full ship entry per faction is
-- exactly the pattern that caused real stat-drift bugs in the other local
-- reference project (`~/Defold/SuperShips/main/config.lua`'s header
-- comments on the old Viper Mk II/Raider and Raven/Malefactor "mirror
-- mismatches"), which is why that project unified onto one shared roster
-- too. Robots (§1, computer-managed only, never player-selectable) don't
-- need a `faction_skins` entry on player-facing ships like this one.
--
-- A future ship that needs to actually deviate from its class's baseline
-- stats would add override fields directly on its own `basic.data` (or
-- `advanced.data`) here, rather than duplicating the whole stat block.

local M = {}

M.SHIPS = {
	["patrol_interceptor"] = {
		class = "Patrol",
		-- `role` (revised-patrol-ships.csv's own Role column): Interceptor.
		role = "Interceptor",
		-- Advanced tier (the whole `advanced` section below) holds the
		-- upgrade price, so the basic entry only carries what it takes to
		-- buy and fly the ship's basic form.
		basic = {
			-- Not for sale: every new pilot starts with it (BSGO: Viper Mark II /
			-- Cylon Raider, starter ships) - the revised CSV leaves all three of
			-- its purchase columns blank.
			price = nil,
			-- Full stat block, taken as-is from revised-patrol-ships.csv (the
			-- Patrol-class source of truth, plan.md §2.1.4) - the BSGO Viper II's
			-- own numbers, superseding this entry's earlier §2.13 figures.
			data = {
				-- Hull Systems
				hull_points = 450,
				hull_recovery_per_sec = 2.5,
				repair_cost_iron = 4500, -- full-repair cost, paid in Iron (§2.6)
				armor = 5,
				critical_defense = 80,

				-- Engine Systems
				avoidance = 510,
				turning_speed_deg_per_sec = 52,
				turning_acceleration_deg_per_sec2 = 55,
				inertial_compensation_m_per_sec = 175,
				acceleration_m_per_sec2 = 13.5,
				speed_m_per_sec = 55,
				boost_speed_m_per_sec = 90,
				boost_cost_hydrogen_per_sec = 0.5, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 4.5,
				ftl_charge_sec = 15,
				ftl_cost_hydrogen_per_ly = 20, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 100,
				power_recharge_per_sec = 5,
				firewall_rating = 100,
				emitter_rating = 100,
				sensor_range_m = 2000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 200,
			},
			-- Component slot counts, revised CSV's own W/H/E/C columns: W 3,
			-- C 2, E 4, H 2.
			components = { W = 3, C = 2, E = 4, H = 2 },
		},
		-- Advanced tier (plan.md §2.1.3, per direct instruction): the extra
		-- component slots the one-way upgrade unlocks, and the statistics it
		-- changes. `price` is charged ON TOP of whatever the basic ship already
		-- cost - no refund of that basic price. Only the fields that CHANGE are
		-- listed; every unlisted stat falls back to `basic.data` above (e.g.
		-- `power_recharge_per_sec` stays 5, `inertial_compensation_m_per_sec`
		-- stays 175).
		advanced = {
			price = { { amount = 30000, currency = "tope" } },
			data = {
				hull_points = 585,
				hull_recovery_per_sec = 4.5,
				repair_cost_iron = 9000,
				turning_speed_deg_per_sec = 55,
				acceleration_m_per_sec2 = 16.2,
				speed_m_per_sec = 60,
				boost_speed_m_per_sec = 110,
				power = 150,
			},
			components = { W = 4, C = 2, E = 5, H = 2 },
		},
		-- Slot positions for the outpost screen's top-down ship visual
		-- (plan.md §2.8/§2.9) - {x, y} offsets in screen-pixel units from
		-- the ship visual panel's own center, same idea as the reference
		-- project's own M.CHASSIS[x].slot_positions
		-- (~/Defold/SuperShips/main/config.lua). ONE list shared by both
		-- tiers (per direct instruction) - each entry's own `tier` field
		-- marks it "basic" (available on the basic hull) or "advanced"
		-- (unlocked only once the ship has been upgraded); a slot with no
		-- `tier` is basic. Advanced-only slots are still SHOWN on the basic
		-- hull, just locked/greyed until the upgrade.
		--
		-- STILL PLACEHOLDER (not real ship-layout design) -
		-- spread across bow/midships/cabin/stern so they at least sit on
		-- the actual hull rather than floating at random; waiting on real
		-- coordinates (plan.md §4). Derived from the hull's own real
		-- geometry: the outpost screen renders the ship visual at
		-- ~49.17 px/meter (see assets/models/patrol_interceptor/ -
		-- "build_patrol_interceptor_model.py" if this ever needs regenerating), so a
		-- point at ship-space (x, z) meters maps to a screen offset of
		-- roughly (x * 49.17, z * 49.17).
		--
		-- `angle_deg` (weapon slots only, plan.md §2.8's new firing-arc
		-- provision): the bearing this mount's firing arc is centered on,
		-- in degrees from the ship's own bow/forward axis - 0 = dead ahead,
		-- positive rotates clockwise toward starboard (+x), matching this
		-- table's own "+y = forward" sense (E1/E3's stern sit at negative
		-- y). Same "STILL PLACEHOLDER, structure not real design" caveat as
		-- the {x, y} coordinates themselves - no targeting/firing code reads
		-- this yet (plan.md §4).
		slot_positions = {
			W1 = { x = -90, y = 100, angle_deg = -15},     -- bow-mounted gun, fires dead ahead
			W2 = { x = 0, y = 250, angle_deg = 0 }, -- port midships gun, forward of the cabin, angled slightly to port
			W3 = { x = 90, y = 100, angle_deg = 15 },   -- starboard midships gun, forward of the cabin, angled slightly to starboard
			W4 = { x = 0, y = 150, angle_deg = 0, tier = "advanced" }, -- advanced-only, centerline, forward-facing
			-- C1/C2 (repositioned per direct instruction - manually adjusted
			-- in the editor, not by a script): side-by-side across the cabin
			-- at the same y, rather than stacked fore/aft at the same x.
			C1 = { x = -50, y = -90 },   -- computer, port side of the cabin
			C2 = { x = 50, y = -90 },     -- computer, centerline of the cabin
			-- H1/H2 (repositioned per direct instruction, same manual
			-- adjustment as C1/C2 above): H1 stays amidships but moved to
			-- the port side; H2 moved from stacked-below-H1 to its own
			-- centerline spot just aft of amidships.
			H1 = { x = -50, y = 0 },    -- hull/armor, port side amidships
			H2 = { x = 50, y = 0 },     -- hull/armor, centerline, just aft of amidships
			-- Per direct instruction: all three engines moved down (further
			-- stern-ward, more negative y) by ~50px; E2 specifically (the
			-- bottom-middle slot - centerline, lowest y of all 9 slots) then
			-- moved back up by 100px on top of that, netting +50 vs. its
			-- original position. E1/E3 now sit at y=-310, just past the
			-- hull's own ~-295 stern extent (see the geometry note above) -
			-- flag if that reads as hanging off the back of the hull once
			-- seen against the real ship_visual image; still well within the
			-- ship_visual panel's own bounds (+-320) either way.
			E1 = { x = -70, y = -340 },
			E2 = { x = -70, y = -250 },
			E3 = { x = 70, y = -340 },
			E4 = { x = 70, y = -250 },
			E5 = { x = 0, y = -180, tier = "advanced" },
		},
		flight_camera = { distance = 28.151, height = 3.292 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Sardine: Preserved approved model: silver flanks, round eyes, equal forked tail.
			accord = { name = "Sardine", model = "/assets/models/patrol_interceptor/patrol_interceptor.model", weapon_gui = "<TBD>" },
			-- Hummingbird: Needle bill, swept narrow wings and ruby throat.
			swarm = { name = "Hummingbird", model = "/assets/models/patrol_interceptor/hummingbird.model", weapon_gui = "<TBD>" },
		},
	},
	["patrol_support"] = {
		class = "Patrol",
		-- `role` (see `frigate_support`'s own entry for the field's rationale): Support.
		role = "Support",
		basic = {
			-- Purchase price from revised-patrol-ships.csv (BSGO: Raptor / Cylon
			-- Heavy Raider): 75,000 Hydrogen, payable in Hydrogen alone.
			price = { { amount = 75000, currency = "hydrogen" } },
			-- Full stat block, taken as-is from revised-patrol-ships.csv (the
			-- Patrol-class source of truth, plan.md §2.1.4): the BSGO Raptor's own
			-- numbers, superseding the earlier §2.1.1 baseline that stood in here.
			data = {
				-- Hull Systems
				hull_points = 500,
				hull_recovery_per_sec = 3,
				repair_cost_iron = 5000, -- full-repair cost, paid in Iron (§2.6)
				armor = 5,
				critical_defense = 100,

				-- Engine Systems
				avoidance = 500,
				turning_speed_deg_per_sec = 47.5,
				turning_acceleration_deg_per_sec2 = 47.5,
				inertial_compensation_m_per_sec = 100,
				acceleration_m_per_sec2 = 10,
				speed_m_per_sec = 52.5,
				boost_speed_m_per_sec = 77.5,
				boost_cost_hydrogen_per_sec = 0.6, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 5.5,
				ftl_charge_sec = 15,
				ftl_cost_hydrogen_per_ly = 30, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 150,
				power_recharge_per_sec = 5.5,
				firewall_rating = 200,
				emitter_rating = 200,
				sensor_range_m = 3000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 500,
			},
			-- Component slot counts, revised CSV's own W/H/E/C columns: W 3,
			-- C 4, E 2, H 2.
			components = { W = 3, C = 4, E = 2, H = 2 },
		},
		-- Advanced tier (revised-patrol-ships.csv, plan.md §2.1.4): 30,000 Tope
		-- on top of the basic price; adds one Weapon and one Computer slot and
		-- raises hull/recovery/repair and the power pool. Unlisted stats fall
		-- back to `basic.data`.
		advanced = {
			price = { { amount = 30000, currency = "tope" } },
			data = {
				hull_points = 650,
				hull_recovery_per_sec = 5,
				repair_cost_iron = 10000,
				power = 175,
				power_recharge_per_sec = 6,
			},
			components = { W = 4, C = 5, E = 2, H = 2 },
		},
		-- Placeholder layout (revised-patrol-ships.csv gives the slot COUNTS but
		-- no coordinates, so these follow the same rows-of-up-to-4 convention the
		-- Frigate hulls use - plan.md §4): Weapons / Hull / Computers / Engines
		-- bands bow-to-stern, symmetric, an odd count's extra on the centreline,
		-- weapon arcs angling outward (angle_deg = x / 4.5, matching the Frigate
		-- rows). W4 and C5 are `tier = "advanced"` - unlocked by the upgrade
		-- (§2.1.4), shown locked/greyed until then. The FULL advanced set is laid
		-- out so the basic slots keep stable positions.
		slot_positions = {
			W1 = { x = -135, y = 200, angle_deg = -30 },
			W2 = { x = -45, y = 200, angle_deg = -10 },
			W3 = { x = 45, y = 200, angle_deg = 10 },
			W4 = { x = 135, y = 200, angle_deg = 30, tier = "advanced" },
			H1 = { x = -45, y = 0 },
			H2 = { x = 45, y = 0 },
			C1 = { x = -135, y = -160 },
			C2 = { x = -45, y = -160 },
			C3 = { x = 45, y = -160 },
			C4 = { x = 135, y = -160 },
			C5 = { x = 0, y = -240, tier = "advanced" },
			E1 = { x = -45, y = -300 },
			E2 = { x = 45, y = -300 },
		},
		flight_camera = { distance = 27.504, height = 3.212 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Pilotfish: Five dark body bands, streamlined body and service cradles.
			accord = { name = "Pilotfish", model = "/assets/models/patrol_support/pilotfish.model", weapon_gui = "<TBD>" },
			-- Oxpecker: Compact rounded wings, ochre body and red bill.
			swarm = { name = "Oxpecker", model = "/assets/models/patrol_support/oxpecker.model", weapon_gui = "<TBD>" },
		},
	},
	["patrol_assault"] = {
		class = "Patrol",
		-- `role` (see `frigate_support`'s own entry for the field's rationale): Assault.
		role = "Assault",
		basic = {
			-- Purchase price from revised-patrol-ships.csv (BSGO: Rhino /
			-- Marauder): 36,000 Tope.
			price = { { amount = 36000, currency = "tope" } },
			-- Full stat block, taken as-is from revised-patrol-ships.csv (the
			-- Patrol-class source of truth, plan.md §2.1.4): the BSGO Rhino's own
			-- numbers, superseding the earlier §2.13 hull/power-only update.
			data = {
				-- Hull Systems
				hull_points = 715,
				hull_recovery_per_sec = 5.5,
				repair_cost_iron = 11000, -- full-repair cost, paid in Iron (§2.6)
				armor = 10,
				critical_defense = 120,

				-- Engine Systems
				avoidance = 490,
				turning_speed_deg_per_sec = 45,
				turning_acceleration_deg_per_sec2 = 45,
				inertial_compensation_m_per_sec = 100,
				acceleration_m_per_sec2 = 8,
				speed_m_per_sec = 50,
				boost_speed_m_per_sec = 75,
				boost_cost_hydrogen_per_sec = 0.7, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 5,
				ftl_charge_sec = 15,
				ftl_cost_hydrogen_per_ly = 30, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 150,
				power_recharge_per_sec = 5,
				firewall_rating = 150,
				emitter_rating = 150,
				sensor_range_m = 2500, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 250,
			},
			-- Component slot counts, revised CSV's own W/H/E/C columns: W 4,
			-- C 2, E 2, H 5.
			components = { W = 4, C = 2, E = 2, H = 5 },
		},
		-- Advanced tier (revised-patrol-ships.csv, plan.md §2.1.4): 40,000 Tope on
		-- top of the basic price; adds one Weapon slot and raises hull to 750.
		-- Every other stat falls back to `basic.data`.
		advanced = {
			price = { { amount = 40000, currency = "tope" } },
			data = { hull_points = 750 },
			components = { W = 5, C = 2, E = 2, H = 5 },
		},
		-- Placeholder layout - same convention as patrol_support's own note above.
		-- The extra advanced Weapon (W5) sits in a second weapons row on the
		-- centreline, flagged `tier = "advanced"`.
		slot_positions = {
			W1 = { x = -135, y = 200, angle_deg = -30 },
			W2 = { x = -45, y = 200, angle_deg = -10 },
			W3 = { x = 45, y = 200, angle_deg = 10 },
			W4 = { x = 135, y = 200, angle_deg = 30 },
			W5 = { x = 0, y = 100, angle_deg = 0, tier = "advanced" },
			H1 = { x = -135, y = 0 },
			H2 = { x = -45, y = 0 },
			H3 = { x = 45, y = 0 },
			H4 = { x = 135, y = 0 },
			H5 = { x = 0, y = -80 },
			C1 = { x = -45, y = -160 },
			C2 = { x = 45, y = -160 },
			E1 = { x = -45, y = -300 },
			E2 = { x = 45, y = -300 },
		},
		flight_camera = { distance = 26.725, height = 3.211 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Piranha: Deep compressed body, blunt jaw, copper belly and armored bite.
			accord = { name = "Piranha", model = "/assets/models/patrol_assault/piranha.model", weapon_gui = "<TBD>" },
			-- Shrike: Black eye mask, hooked beak and long narrow tail.
			swarm = { name = "Shrike", model = "/assets/models/patrol_assault/shrike.model", weapon_gui = "<TBD>" },
		},
	},
	["patrol_tactical"] = {
		class = "Patrol",
		-- `role` (see `frigate_support`'s own entry for the field's rationale): Tactical.
		role = "Tactical",
		basic = {
			-- Purchase price from revised-patrol-ships.csv (BSGO: Viper Mark VII /
			-- Cylon War Raider): 45,000 Tope.
			price = { { amount = 45000, currency = "tope" } },
			-- Full stat block, taken as-is from revised-patrol-ships.csv (the
			-- Patrol-class source of truth, plan.md §2.1.4): the BSGO Viper VII's
			-- own numbers, superseding the earlier §2.1.1 baseline.
			data = {
				-- Hull Systems
				hull_points = 585,
				hull_recovery_per_sec = 4.5,
				repair_cost_iron = 9000, -- full-repair cost, paid in Iron (§2.6)
				armor = 5,
				critical_defense = 80,

				-- Engine Systems
				avoidance = 510,
				turning_speed_deg_per_sec = 50,
				turning_acceleration_deg_per_sec2 = 55,
				inertial_compensation_m_per_sec = 100,
				acceleration_m_per_sec2 = 12,
				speed_m_per_sec = 55,
				boost_speed_m_per_sec = 85,
				boost_cost_hydrogen_per_sec = 0.75, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 4.5,
				ftl_charge_sec = 15,
				ftl_cost_hydrogen_per_ly = 30, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 150,
				power_recharge_per_sec = 5,
				firewall_rating = 100,
				emitter_rating = 100,
				sensor_range_m = 2000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 200,
			},
			-- Component slot counts, revised CSV's own W/H/E/C columns: W 4,
			-- C 3, E 3, H 3.
			components = { W = 4, C = 3, E = 3, H = 3 },
		},
		-- Advanced tier (revised-patrol-ships.csv, plan.md §2.1.4). NOTE its
		-- price is in VALOUR, not Tope - the only ship priced in the PvP
		-- currency so far (§2.6). Nothing grants Valour yet (PvP rewards are
		-- unimplemented), so this tier cannot actually be bought until they
		-- exist; flagged in plan.md §2.6/§4. Adds one Weapon slot and raises
		-- hull/recovery and power recharge.
		advanced = {
			price = { { amount = 30000, currency = "valour" } },
			data = {
				hull_points = 720,
				hull_recovery_per_sec = 5.25,
				power_recharge_per_sec = 6,
			},
			components = { W = 5, C = 3, E = 3, H = 3 },
		},
		-- Placeholder layout - same convention as patrol_support's own note above.
		-- The extra advanced Weapon (W5) sits in a second weapons row on the
		-- centreline, flagged `tier = "advanced"`.
		slot_positions = {
			W1 = { x = -135, y = 200, angle_deg = -30 },
			W2 = { x = -45, y = 200, angle_deg = -10 },
			W3 = { x = 45, y = 200, angle_deg = 10 },
			W4 = { x = 135, y = 200, angle_deg = 30 },
			W5 = { x = 0, y = 100, angle_deg = 0, tier = "advanced" },
			H1 = { x = -90, y = 0 },
			H2 = { x = 0, y = 0 },
			H3 = { x = 90, y = 0 },
			C1 = { x = -90, y = -160 },
			C2 = { x = 0, y = -160 },
			C3 = { x = 90, y = -160 },
			E1 = { x = -90, y = -300 },
			E2 = { x = 0, y = -300 },
			E3 = { x = 90, y = -300 },
		},
		flight_camera = { distance = 26.534, height = 3.137 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Anglerfish: Round head, broad mouth and a luminous-tipped forward sensor lure.
			accord = { name = "Anglerfish", model = "/assets/models/patrol_tactical/anglerfish.model", weapon_gui = "<TBD>" },
			-- Kingfisher: Long spear bill, compact wings and swept blue crest.
			swarm = { name = "Kingfisher", model = "/assets/models/patrol_tactical/kingfisher.model", weapon_gui = "<TBD>" },
		},
	},
	["escort_interceptor"] = {
		class = "Escort",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Scythe / Banshee), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 600000, currency = "hydrogen" } },
			-- Full stat block: the §2.1.1 universal baseline. Per direct instruction
			-- the **Hull and Computer Systems** numbers stay here rather than taking
			-- the Rhino figures - the Rhino is `patrol_assault`'s own BSGO
			-- counterpart, NOT an Escort-tier reference, and plan.md §2.13 records
			-- no real hull/power for this ship's own counterpart. Left as the shared
			-- placeholder (650 / 5, 175 / 6) rather than an invented number
			-- (§0/§4), pending real per-ship tuning.
			data = {
				-- Hull Systems
				hull_points = 650,
				hull_recovery_per_sec = 5,
				repair_cost_iron = 10000, -- full-repair cost, paid in Iron (§2.6)
				armor = 5,
				critical_defense = 100,

				-- Engine Systems
				avoidance = 500,
				turning_speed_deg_per_sec = 47.5,
				turning_acceleration_deg_per_sec2 = 47.5,
				inertial_compensation_m_per_sec = 100,
				acceleration_m_per_sec2 = 10,
				speed_m_per_sec = 52.5,
				boost_speed_m_per_sec = 77.5,
				boost_cost_hydrogen_per_sec = 0.6, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 5.5,
				ftl_charge_sec = 15,
				ftl_cost_hydrogen_per_ly = 30, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 175,
				power_recharge_per_sec = 6,
				firewall_rating = 200,
				emitter_rating = 200,
				sensor_range_m = 3000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 500,
			},
			-- Component slot counts and their screen positions are NOT set yet -
			-- unlike Patrol Interceptor, no source number (Viper Mk II tier or otherwise)
			-- has been given for Escort, and plan.md's own rule is "don't invent
			-- unconfirmed numbers" (§0/§4). Deliberately left empty rather than
			-- guessed: the outpost screen already handles a ship with zero
			-- slot_positions correctly (0 markers shown, not a crash - proven by
			-- outpost_harness2.lua's injected "escort_test" ship). Flagged in
			-- plan.md §4 pending real Escort-tier fitting design.
			components = {},
		},
		slot_positions = {},
		flight_camera = { distance = 102.074, height = 13.338 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Barracuda: Long narrow body, projecting lower jaw and two separate dorsal fins.
			accord = { name = "Barracuda", model = "/assets/models/escort_interceptor/barracuda.model", weapon_gui = "<TBD>" },
			-- Falcon: Pointed swept wings, short hooked beak and cheek mask.
			swarm = { name = "Falcon", model = "/assets/models/escort_interceptor/falcon.model", weapon_gui = "<TBD>" },
		},
	},
	["escort_support"] = {
		class = "Escort",
		-- `role` (see `frigate_support`'s own entry for the field's rationale): Support.
		role = "Support",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Glaive / Spectre), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 60000, currency = "tope" } },
			-- Full stat block: the §2.1.1 universal baseline. Per direct instruction
			-- the **Hull and Computer Systems** numbers stay here rather than taking
			-- the Rhino figures - the Rhino is `patrol_assault`'s own BSGO
			-- counterpart, NOT an Escort-tier reference, and plan.md §2.13 records
			-- no real hull/power for this ship's own counterpart. Left as the shared
			-- placeholder (650 / 5, 175 / 6) rather than an invented number
			-- (§0/§4), pending real per-ship tuning.
			data = {
				-- Hull Systems
				hull_points = 650,
				hull_recovery_per_sec = 5,
				repair_cost_iron = 10000, -- full-repair cost, paid in Iron (§2.6)
				armor = 5,
				critical_defense = 100,

				-- Engine Systems
				avoidance = 500,
				turning_speed_deg_per_sec = 47.5,
				turning_acceleration_deg_per_sec2 = 47.5,
				inertial_compensation_m_per_sec = 100,
				acceleration_m_per_sec2 = 10,
				speed_m_per_sec = 52.5,
				boost_speed_m_per_sec = 77.5,
				boost_cost_hydrogen_per_sec = 0.6, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 5.5,
				ftl_charge_sec = 15,
				ftl_cost_hydrogen_per_ly = 30, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 175,
				power_recharge_per_sec = 6,
				firewall_rating = 200,
				emitter_rating = 200,
				sensor_range_m = 3000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 500,
			},
			-- Same as the other Escort/Frigate-tier ships: no confirmed slot-count
			-- number exists yet, so left empty rather than guessed (§0/§4).
			components = {},
		},
		slot_positions = {},
		flight_camera = { distance = 95.681, height = 12.650 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Remora: Flattened head and long ribbed dorsal docking disc.
			accord = { name = "Remora", model = "/assets/models/escort_support/remora.model", weapon_gui = "<TBD>" },
			-- Egret: White feather armor, slender S-neck and long straight bill.
			swarm = { name = "Egret", model = "/assets/models/escort_support/egret.model", weapon_gui = "<TBD>" },
		},
	},
	["escort_tactical"] = {
		class = "Escort",
		-- `role` (see `frigate_support`'s own entry for the field's rationale): Tactical.
		role = "Tactical",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Halberd / Liche), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 75000, currency = "tope" } },
			-- Full stat block sourced from https://bsgo.fandom.com/wiki/Liche (per
			-- direct instruction: "apply the stats from the liche to the Osprey") -
			-- Liche is the wiki's own Cylon-faction Escort-class counterpart this
			-- chassis' Swarm skin (Osprey) already visually reinterprets (this
			-- ship's model was tools/build_osprey_model.py's own original design,
			-- not sourced - only these NUMBERS come from the wiki page). Stats are
			-- per-CHASSIS, not per-faction-skin (§2.1.2's own "only name/model/
			-- weapon_gui differ per faction, every stat is identical" data model -
			-- there is no separate Lionfish stat block to leave at the baseline),
			-- so this replaces the shared universal-baseline block below for BOTH
			-- Lionfish and Osprey, not Osprey alone. `repair_cost_iron` is left at
			-- its existing baseline value - the wiki page's own stats don't include
			-- a repair cost, only a 75,000-cubit PURCHASE price (not a Tope
			-- conversion this project has decided yet, so not applied either -
			-- §0/§4, don't invent unconfirmed numbers). Equipment Slots (Liche:
			-- Weapon 6/Hull 3/Engine 3/Computer 3) also NOT applied here - that's
			-- component/slot-position data, not this stat block, and this chassis
			-- has no slot_positions layout to pair real counts with yet (still
			-- empty below); flag if that should be filled in too.
			data = {
				-- Hull Systems
				hull_points = 1950,
				hull_recovery_per_sec = 15,
				repair_cost_iron = 10000, -- full-repair cost, paid in Iron (§2.6) - NOT from the Liche page, see this entry's own header comment
				armor = 25,
				critical_defense = 100,

				-- Engine Systems
				avoidance = 260,
				turning_speed_deg_per_sec = 25,
				turning_acceleration_deg_per_sec2 = 25,
				inertial_compensation_m_per_sec = 50,
				acceleration_m_per_sec2 = 5,
				speed_m_per_sec = 40,
				boost_speed_m_per_sec = 60,
				boost_cost_hydrogen_per_sec = 2.7, -- renamed from the wiki's own Tylium unit (§2.6)

				-- FTL Systems
				ftl_range_ly = 7.5,
				ftl_charge_sec = 20,
				ftl_cost_hydrogen_per_ly = 80, -- renamed from the wiki's own Tylium unit (§2.6)

				-- Computer Systems
				power = 300,
				power_recharge_per_sec = 10,
				firewall_rating = 150,
				emitter_rating = 150,
				sensor_range_m = 3000, -- renamed from source's "Dradis Range" (§0) - unchanged, the wiki's own value matches the baseline exactly
				visual_range_m = 300,
			},
			-- No confirmed slot-count number exists yet for this ship, so left
			-- empty rather than guessed (§0/§4).
			components = {},
		},
		slot_positions = {},
		flight_camera = { distance = 108.507, height = 13.124 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Lionfish: Striped body, radiating sensor spines and large fan-shaped pectorals.
			accord = { name = "Lionfish", model = "/assets/models/escort_tactical/lionfish.model", weapon_gui = "<TBD>" },
			-- Osprey: Bent M-shaped wings, pale head and dark eye stripe.
			swarm = { name = "Osprey", model = "/assets/models/escort_tactical/osprey.model", weapon_gui = "<TBD>" },
		},
	},
	["escort_assault"] = {
		class = "Escort",
		-- `role` (see `frigate_support`'s own entry for the field's rationale): Assault.
		role = "Assault",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Maul / Wraith), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 600000, currency = "hydrogen" } },
			-- Full stat block: the §2.1.1 universal baseline. Per direct instruction
			-- the **Hull and Computer Systems** numbers stay here rather than taking
			-- the Rhino figures - the Rhino is `patrol_assault`'s own BSGO
			-- counterpart, NOT an Escort-tier reference, and plan.md §2.13 records
			-- no real hull/power for this ship's own counterpart. Left as the shared
			-- placeholder (650 / 5, 175 / 6) rather than an invented number
			-- (§0/§4), pending real per-ship tuning.
			data = {
				-- Hull Systems
				hull_points = 650,
				hull_recovery_per_sec = 5,
				repair_cost_iron = 10000, -- full-repair cost, paid in Iron (§2.6)
				armor = 5,
				critical_defense = 100,

				-- Engine Systems
				avoidance = 500,
				turning_speed_deg_per_sec = 47.5,
				turning_acceleration_deg_per_sec2 = 47.5,
				inertial_compensation_m_per_sec = 100,
				acceleration_m_per_sec2 = 10,
				speed_m_per_sec = 52.5,
				boost_speed_m_per_sec = 77.5,
				boost_cost_hydrogen_per_sec = 0.6, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 5.5,
				ftl_charge_sec = 15,
				ftl_cost_hydrogen_per_ly = 30, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 175,
				power_recharge_per_sec = 6,
				firewall_rating = 200,
				emitter_rating = 200,
				sensor_range_m = 3000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 500,
			},
			-- Same as the other Escort/Frigate-tier ships: no confirmed slot-count
			-- number exists yet, so left empty rather than guessed (§0/§4).
			components = {},
		},
		slot_positions = {},
		flight_camera = { distance = 82.545, height = 12.938 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Moray: Straight symmetrical eel body, centered dorsal ribbon and heavy jaw.
			accord = { name = "Moray", model = "/assets/models/escort_assault/moray.model", weapon_gui = "<TBD>" },
			-- Goshawk: Broad rounded wings, long barred tail and pale eyebrow.
			swarm = { name = "Goshawk", model = "/assets/models/escort_assault/goshawk.model", weapon_gui = "<TBD>" },
		},
	},
	["frigate_support"] = {
		class = "Frigate",
		-- `role` (new field, plan.md §2.1.2's Interceptor/Support/Assault/Tactical
		-- naming-matrix rows): Support. Deliberately separate from `class` above,
		-- which stays the size tier (Patrol/Escort/Frigate/Carrier) - outpost.gui_script
		-- already reads `ship.class` for display and module-compatibility filtering,
		-- so that field couldn't be repurposed to hold the role instead. Purely
		-- descriptive for now, same as `components`/`slot_positions` being left
		-- empty below - not yet wired into any gameplay logic. Patrol Interceptor/Escort Interceptor
		-- predate this dimension and are Interceptor-row per the naming matrix, but
		-- don't have a `role` field set retroactively (out of scope here).
		role = "Support",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Vanir / Hel), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 2000000, currency = "hydrogen" } },
			-- Full stat block and slot counts: the reference game's Vanir (a
			-- Command-role line ship, bsgo.fandom.com/wiki/Vanir), per direct
			-- instruction - plain numbers, a balancing fact not creative
			-- expression (§0), same footing as Patrol Interceptor's Viper Mk II
			-- slot counts. Source units renamed as elsewhere: Titanium repair
			-- cost -> Iron, Tylium fuel -> Hydrogen, Dradis -> sensor range.
			-- Not carried over: its level-20 requirement and 2,000,000 purchase
			-- price (no rank gating yet; prices come from session.lua), and its
			-- Command role bonus (no FTL-transponder module exists).
			data = {
				-- Hull Systems
				hull_points = 3500,
				hull_recovery_per_sec = 19,
				repair_cost_iron = 35000, -- full-repair cost, paid in Iron (§2.6)
				armor = 40,
				critical_defense = 100,

				-- Engine Systems
				avoidance = 50,
				turning_speed_deg_per_sec = 9,
				turning_acceleration_deg_per_sec2 = 9,
				inertial_compensation_m_per_sec = 50,
				acceleration_m_per_sec2 = 2,
				speed_m_per_sec = 27.5,
				boost_speed_m_per_sec = 42.5,
				boost_cost_hydrogen_per_sec = 5.4, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 11,
				ftl_charge_sec = 25,
				ftl_cost_hydrogen_per_ly = 250, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 650,
				power_recharge_per_sec = 28,
				firewall_rating = 200,
				emitter_rating = 200,
				sensor_range_m = 4000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 1000,
			},
			-- Vanir slot counts (see the stat block's comment above);
			-- Fitting screen positions below.
			components = { W = 6, C = 4, E = 2, H = 2 },
		},
		-- Laid out over both faction silhouettes (main/images/topdown/,
		-- 440 x 640 px, centre origin, +y = bow, +x = starboard): rows of
		-- up to 4 from bow to stern - Weapons, Hull, Computers, Engines -
		-- symmetric, with an odd count's extra slot on the centreline.
		-- Weapon arcs angle outward with distance from the centreline.
		-- All basic (this ship has no advanced tier).
		slot_positions = {
			W1 = { x = -135, y = 200, angle_deg = -30 },
			W2 = { x = -45, y = 200, angle_deg = -10 },
			W3 = { x = 45, y = 200, angle_deg = 10 },
			W4 = { x = 135, y = 200, angle_deg = 30 },
			W5 = { x = -45, y = 100, angle_deg = -10 },
			W6 = { x = 45, y = 100, angle_deg = 10 },
			H1 = { x = -45, y = 0 },
			H2 = { x = 45, y = 0 },
			C1 = { x = -135, y = -100 },
			C2 = { x = -45, y = -100 },
			C3 = { x = 45, y = -100 },
			C4 = { x = 135, y = -100 },
			E1 = { x = -45, y = -200 },
			E2 = { x = 45, y = -200 },
		},
		flight_camera = { distance = 353.428, height = 55.768 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Manta Ray: Broad swept ray disc, paired cephalic lobes and slender trailing tail.
			accord = { name = "Manta Ray", model = "/assets/models/frigate_support/manta_ray.model", weapon_gui = "<TBD>" },
			-- Pelican: Broad wings, long bill and large armored throat pouch.
			swarm = { name = "Pelican", model = "/assets/models/frigate_support/pelican.model", weapon_gui = "<TBD>" },
		},
	},
	["frigate_interceptor"] = {
		class = "Frigate",
		-- `role` (see `frigate_support` above for the field's own rationale): Interceptor.
		role = "Interceptor",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Fenrir / Aesir), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 135000, currency = "tope" } },
			-- Full stat block and slot counts: the reference game's Fenrir (an
			-- Interceptor-role line ship, bsgo.fandom.com/wiki/Fenrir), per direct
			-- instruction - same sourcing and unit renames as `frigate_support`'s
			-- Vanir numbers above (§0). Not carried over, for the same reasons:
			-- its level-20 requirement and 135,000-cubit purchase price.
			data = {
				-- Hull Systems
				hull_points = 4290,
				hull_recovery_per_sec = 33,
				repair_cost_iron = 66000, -- full-repair cost, paid in Iron (§2.6)
				armor = 40,
				critical_defense = 80,

				-- Engine Systems
				avoidance = 70,
				turning_speed_deg_per_sec = 10,
				turning_acceleration_deg_per_sec2 = 10,
				inertial_compensation_m_per_sec = 50,
				acceleration_m_per_sec2 = 2.5,
				speed_m_per_sec = 30,
				boost_speed_m_per_sec = 45,
				boost_cost_hydrogen_per_sec = 4.5, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 9,
				ftl_charge_sec = 25,
				ftl_cost_hydrogen_per_ly = 250, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 750,
				power_recharge_per_sec = 25,
				firewall_rating = 100,
				emitter_rating = 100,
				sensor_range_m = 3000, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 300,
			},
			-- Fenrir slot counts (see the stat block's comment above);
			-- Fitting screen positions below.
			components = { W = 8, C = 2, E = 5, H = 2 },
		},
		-- Laid out over both faction silhouettes (main/images/topdown/,
		-- 440 x 640 px, centre origin, +y = bow, +x = starboard): rows of
		-- up to 4 from bow to stern - Weapons, Hull, Computers, Engines -
		-- symmetric, with an odd count's extra slot on the centreline.
		-- Weapon arcs angle outward with distance from the centreline.
		-- All basic (this ship has no advanced tier).
		slot_positions = {
			W1 = { x = -135, y = 250, angle_deg = -30 },
			W2 = { x = -45, y = 250, angle_deg = -10 },
			W3 = { x = 45, y = 250, angle_deg = 10 },
			W4 = { x = 135, y = 250, angle_deg = 30 },
			W5 = { x = -135, y = 150, angle_deg = -30 },
			W6 = { x = -45, y = 150, angle_deg = -10 },
			W7 = { x = 45, y = 150, angle_deg = 10 },
			W8 = { x = 135, y = 150, angle_deg = 30 },
			H1 = { x = -45, y = 50 },
			H2 = { x = 45, y = 50 },
			C1 = { x = -45, y = -50 },
			C2 = { x = 45, y = -50 },
			E1 = { x = -135, y = -150 },
			E2 = { x = -45, y = -150 },
			E3 = { x = 45, y = -150 },
			E4 = { x = 135, y = -150 },
			E5 = { x = 0, y = -250 },
		},
		flight_camera = { distance = 403.553, height = 49.803 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Marlin: Long spear bill, slender fast hull and crescent caudal fin.
			accord = { name = "Marlin", model = "/assets/models/frigate_interceptor/marlin.model", weapon_gui = "<TBD>" },
			-- Frigatebird: Very long angular wings, forked tail and red throat module.
			swarm = { name = "Frigatebird", model = "/assets/models/frigate_interceptor/frigatebird.model", weapon_gui = "<TBD>" },
		},
	},
	["frigate_tactical"] = {
		class = "Frigate",
		-- `role` (see `frigate_support` above for the field's own rationale): Tactical.
		role = "Tactical",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Gungnir / Nidhogg), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 250000, currency = "tope" } },
			-- Full stat block and slot counts: the reference game's Gungnir (a
			-- Multi-Role line ship, bsgo.fandom.com/wiki/Gungnir), per direct
			-- instruction - same sourcing and unit renames as `frigate_support`'s
			-- Vanir numbers above (§0). Not carried over, for the same reasons:
			-- its level-20 requirement and 250,000-cubit purchase price.
			data = {
				-- Hull Systems
				hull_points = 4550,
				hull_recovery_per_sec = 35,
				repair_cost_iron = 70000, -- full-repair cost, paid in Iron (§2.6)
				armor = 40,
				critical_defense = 100,

				-- Engine Systems
				avoidance = 50,
				turning_speed_deg_per_sec = 10,
				turning_acceleration_deg_per_sec2 = 10,
				inertial_compensation_m_per_sec = 50,
				acceleration_m_per_sec2 = 2,
				speed_m_per_sec = 30,
				boost_speed_m_per_sec = 45,
				boost_cost_hydrogen_per_sec = 8.1, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 10,
				ftl_charge_sec = 25,
				ftl_cost_hydrogen_per_ly = 250, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 750,
				power_recharge_per_sec = 25,
				firewall_rating = 150,
				emitter_rating = 150,
				sensor_range_m = 3500, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 350,
			},
			-- Gungnir slot counts (see the stat block's comment above);
			-- Fitting screen positions below.
			components = { W = 8, C = 3, E = 3, H = 3 },
		},
		-- Laid out over both faction silhouettes (main/images/topdown/,
		-- 440 x 640 px, centre origin, +y = bow, +x = starboard): rows of
		-- up to 4 from bow to stern - Weapons, Hull, Computers, Engines -
		-- symmetric, with an odd count's extra slot on the centreline.
		-- Weapon arcs angle outward with distance from the centreline.
		-- All basic (this ship has no advanced tier).
		slot_positions = {
			W1 = { x = -135, y = 200, angle_deg = -30 },
			W2 = { x = -45, y = 200, angle_deg = -10 },
			W3 = { x = 45, y = 200, angle_deg = 10 },
			W4 = { x = 135, y = 200, angle_deg = 30 },
			W5 = { x = -135, y = 100, angle_deg = -30 },
			W6 = { x = -45, y = 100, angle_deg = -10 },
			W7 = { x = 45, y = 100, angle_deg = 10 },
			W8 = { x = 135, y = 100, angle_deg = 30 },
			H1 = { x = -90, y = 0 },
			H2 = { x = 0, y = 0 },
			H3 = { x = 90, y = 0 },
			C1 = { x = -90, y = -100 },
			C2 = { x = 0, y = -100 },
			C3 = { x = 90, y = -100 },
			E1 = { x = -90, y = -200 },
			E2 = { x = 0, y = -200 },
			E3 = { x = 90, y = -200 },
		},
		flight_camera = { distance = 416.144, height = 54.873 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Hammerhead: Broad transverse hammer head with sensors at both ends.
			accord = { name = "Hammerhead", model = "/assets/models/frigate_tactical/hammerhead.model", weapon_gui = "<TBD>" },
			-- Harpy Eagle: Massive broad wings, slate chest and a split crown crest.
			swarm = { name = "Harpy Eagle", model = "/assets/models/frigate_tactical/harpy_eagle.model", weapon_gui = "<TBD>" },
		},
	},
	["frigate_assault"] = {
		class = "Frigate",
		-- `role` (see `frigate_support` above for the field's own rationale): Assault.
		role = "Assault",
		-- No `advanced` section: no confirmed advanced tier yet (§0/§4).
		basic = {
			-- Purchase price from bsgo.fandom.com (Jotunn / Jormung), as-is: cubits -> Tope,
			-- Tylium -> Hydrogen. Same for both factions (the two are counterparts there).
			price = { { amount = 2000000, currency = "hydrogen" } },
			-- Full stat block and slot counts: the reference game's Jotunn (an
			-- Assault-role line ship, bsgo.fandom.com/wiki/Jotunn), per direct
			-- instruction - same sourcing and unit renames as `frigate_support`'s
			-- Vanir numbers above (§0). Not carried over, for the same reasons:
			-- its level-20 requirement and 2,000,000 purchase price.
			data = {
				-- Hull Systems
				hull_points = 4500,
				hull_recovery_per_sec = 20.6,
				repair_cost_iron = 37000, -- full-repair cost, paid in Iron (§2.6)
				armor = 45,
				critical_defense = 120,

				-- Engine Systems
				avoidance = 30,
				turning_speed_deg_per_sec = 8,
				turning_acceleration_deg_per_sec2 = 8,
				inertial_compensation_m_per_sec = 50,
				acceleration_m_per_sec2 = 1.5,
				speed_m_per_sec = 25,
				boost_speed_m_per_sec = 40,
				boost_cost_hydrogen_per_sec = 6.3, -- Hydrogen fuel (§2.6)

				-- FTL Systems
				ftl_range_ly = 10,
				ftl_charge_sec = 25,
				ftl_cost_hydrogen_per_ly = 250, -- Hydrogen fuel (§2.6)

				-- Computer Systems
				power = 500,
				power_recharge_per_sec = 25,
				firewall_rating = 150,
				emitter_rating = 150,
				sensor_range_m = 3500, -- renamed from source's "Dradis Range" (§0)
				visual_range_m = 350,
			},
			-- Jotunn slot counts (see the stat block's comment above);
			-- Fitting screen positions below.
			components = { W = 6, C = 2, E = 2, H = 4 },
		},
		-- Laid out over both faction silhouettes (main/images/topdown/,
		-- 440 x 640 px, centre origin, +y = bow, +x = starboard): rows of
		-- up to 4 from bow to stern - Weapons, Hull, Computers, Engines -
		-- symmetric, with an odd count's extra slot on the centreline.
		-- Weapon arcs angle outward with distance from the centreline.
		-- All basic (this ship has no advanced tier).
		slot_positions = {
			W1 = { x = -135, y = 200, angle_deg = -30 },
			W2 = { x = -45, y = 200, angle_deg = -10 },
			W3 = { x = 45, y = 200, angle_deg = 10 },
			W4 = { x = 135, y = 200, angle_deg = 30 },
			W5 = { x = -45, y = 100, angle_deg = -10 },
			W6 = { x = 45, y = 100, angle_deg = 10 },
			H1 = { x = -135, y = 0 },
			H2 = { x = -45, y = 0 },
			H3 = { x = 45, y = 0 },
			H4 = { x = 135, y = 0 },
			C1 = { x = -45, y = -100 },
			C2 = { x = 45, y = -100 },
			E1 = { x = -45, y = -200 },
			E2 = { x = 45, y = -200 },
		},
		flight_camera = { distance = 385.522, height = 50.957 },
		faction_skins = {
			-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.
			-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.
			-- Tiger Shark: Heavy blunt shark head, dark flank bars and asymmetric caudal lobes.
			accord = { name = "Tiger Shark", model = "/assets/models/frigate_assault/tiger_shark.model", weapon_gui = "<TBD>" },
			-- Golden Eagle: Broad fingered wings and golden neck/shoulder armor.
			swarm = { name = "Golden Eagle", model = "/assets/models/frigate_assault/golden_eagle.model", weapon_gui = "<TBD>" },
		},
	},
}

return M
