-- GENERATED by tools/sync_server_rules.py from main/data/modules/engine_modules.lua - edit that file, not this copy.
-- Engine module entries (plan.md §2.8). First pass, Patrol-tier only, per
-- direct instruction ("concentrate primarily on patrol class as we can
-- extrapolate to the other classes") - built from real BSGO research
-- (plan.md's Hull/Engine/Computer research pass): the source material
-- confirms Engine modules affect speed, boost speed, or turning rate, and
-- names one real item outright - "Engine Gyros" (a turning-speed booster) -
-- carried straight into `name` below with no renaming decision needed,
-- same "already a plain, non-flavor-text name" treatment as the real
-- Autopilot Module/Mineral Analysis Module names computer_modules.lua's
-- own Asteroid Analyser was inspired by. A speed/boost-speed booster is
-- also confirmed to exist as a category but no specific real name was
-- found for it - "Thruster Array" below is this project's own label for
-- that real category (§0), not a source name.
--
-- A separate real capability - Slide Thrusters, decoupling heading from
-- the flight path for a few seconds - is also confirmed (real ability,
-- no real numbers given for its duration/cost anywhere found), distinct
-- from the passive stat-boost items - an ACTIVE one-shot ability instead.
-- Ties into input/game.input_binding's already-reserved "slide" action
-- (§2.10) - flight mode itself doesn't implement the actual slide-drift
-- movement behavior yet (§4), same "binding reserved, behavior not built"
-- footing every other unimplemented flight action is on.
--
-- `stats`: which of ships.lua's own `data` stat fields (§2.1.1) this
-- module boosts - a schema provision only, no bonus AMOUNT given per
-- entry, per §0/§4's "don't invent unconfirmed numbers" rule (BSGO never
-- published real numeric values for Engine modules anywhere found - only
-- Weapons had real published stats). `icon`: each entry now has its own
-- dedicated icon (per direct instruction), generated by
-- tools/build_module_icons.py - the same colored thruster-bell silhouette
-- every Engine module shares, one fill color per entry. Was briefly
-- "Octagon Empty" (a generic neutral placeholder) after a REAL BUG, found
-- live: the original icon was "Octagon E", the SAME icon
-- SLOT_EMPTY_ICON.engine already uses for an unfilled Engine slot
-- (main/outpost.gui_script) - installing one of these modules was
-- therefore visually indistinguishable from the slot staying empty (Scrip
-- was correctly spent and the module was correctly installed, but nothing
-- looked different on the ship).

local M = {}

M.ENGINE_MODULES = {
	["engine_gyros_patrol"] = {
		name = "Engine Gyros",
		type = "engine",
		behavior = "passive", -- §2.8: Engine modules are either passive or one-shot-active, never toggle
		stats = { "turning_speed_deg_per_sec" },
		ship_class = "Patrol",
		icon = "engine_gyros_patrol",
	},
	["thruster_array_patrol"] = {
		name = "Thruster Array",
		type = "engine",
		behavior = "passive",
		stats = { "speed_m_per_sec", "boost_speed_m_per_sec" },
		ship_class = "Patrol",
		icon = "thruster_array_patrol",
	},
	-- Real confirmed capability (source material: Slide Thrusters -
	-- decouples heading from the flight path for a few seconds), distinct
	-- from the passive boosters above - an ACTIVE one-shot ability, same
	-- footing as computer_modules.lua's own Asteroid Analyser. No
	-- power_draw/cooldown/wear_per_use or duration given anywhere real -
	-- omitted rather than guessed (plan.md §4).
	["slide_thrusters_patrol"] = {
		name = "Slide Thrusters",
		type = "engine",
		behavior = "active",
		ship_class = "Patrol",
		icon = "slide_thrusters_patrol",
	},
}

return M
