-- GENERATED by tools/sync_server_rules.py from main/data/modules/hull_modules.lua - edit that file, not this copy.
-- Hull module entries (plan.md §2.8). First pass, Patrol-tier only, per
-- direct instruction ("concentrate primarily on patrol class as we can
-- extrapolate to the other classes") - built from real BSGO research
-- (plan.md's Hull/Engine/Computer research pass): the source wiki gives a
-- confirmed real TAXONOMY of 6 Hull plating types - single-stat (Armor
-- Value only, or Critical Defense only) and combo variants (Hull Points +
-- Armor, Hull Points + Crit Defense, Armor + Crit Defense, all three) -
-- with combo variants giving LESS of each individual stat than a
-- single-stat item (a real breadth-vs-magnitude trade-off, not modeled).
-- A separate real capability - in-flight hull repair - is also confirmed
-- (distinct from the passive stat-boost items, an ACTIVE ability instead).
--
-- Naming: the source wiki's own combo-tier names use an unexplained "HT"
-- prefix (e.g. "HT Plating", "HT Composite Plating") - no source found
-- actually expands what "HT" stands for, so rather than carry an
-- unexplained acronym into this project, the combo tiers are named
-- "Reinforced <X>" instead (same real taxonomy/structure, an original
-- label - §0, same treatment weapons_autocannons.lua's weapon names and
-- computer_modules.lua's Asteroid Analyser already gave their own real
-- BSGO counterparts).
--
-- `stats`: which of ships.lua's own `data` stat fields (§2.1.1) this
-- module boosts - a schema provision only, no bonus AMOUNT given per
-- entry. Per §0/§4's "don't invent unconfirmed numbers" rule: BSGO never
-- published real numeric values for Hull modules anywhere found (only
-- Weapons had real published stats) - same treatment weapons_autocannons.lua
-- already gives its own still-undecided `arc` default before the user
-- supplied one. `icon`: each entry now has its own dedicated icon (per
-- direct instruction), generated by tools/build_module_icons.py - the
-- same colored pentagon "armor plate" silhouette every Hull module
-- shares, one fill color per entry so they're distinguishable from each
-- other. Was briefly "Octagon Empty" (a generic neutral placeholder)
-- after a REAL BUG, found live: the original icon was "Octagon H", the
-- SAME icon SLOT_EMPTY_ICON.hull already uses for an unfilled Hull slot
-- (main/outpost.gui_script) - installing one of these modules was
-- therefore visually indistinguishable from the slot staying empty
-- (Tope was correctly spent and the module was correctly installed, but
-- nothing looked different on the ship).

local M = {}

M.HULL_MODULES = {
	["armor_plating_patrol"] = {
		name = "Armor Plating",
		type = "hull",
		behavior = "passive", -- §2.8: Hull modules are either passive or one-shot-active, never toggle
		stats = { "armor" },
		ship_class = "Patrol",
		icon = "armor_plating_patrol",
	},
	["reinforced_plating_patrol"] = {
		name = "Reinforced Plating",
		type = "hull",
		behavior = "passive",
		stats = { "critical_defense" },
		ship_class = "Patrol",
		icon = "reinforced_plating_patrol",
	},
	["composite_plating_patrol"] = {
		name = "Composite Plating",
		type = "hull",
		behavior = "passive",
		stats = { "hull_points", "armor" },
		ship_class = "Patrol",
		icon = "composite_plating_patrol",
	},
	["reinforced_hull_plating_patrol"] = {
		name = "Reinforced Hull Plating",
		type = "hull",
		behavior = "passive",
		stats = { "hull_points", "critical_defense" },
		ship_class = "Patrol",
		icon = "reinforced_hull_plating_patrol",
	},
	["reinforced_armor_plating_patrol"] = {
		name = "Reinforced Armor Plating",
		type = "hull",
		behavior = "passive",
		stats = { "armor", "critical_defense" },
		ship_class = "Patrol",
		icon = "reinforced_armor_plating_patrol",
	},
	["reinforced_composite_plating_patrol"] = {
		name = "Reinforced Composite Plating",
		type = "hull",
		behavior = "passive",
		stats = { "hull_points", "armor", "critical_defense" },
		ship_class = "Patrol",
		icon = "reinforced_composite_plating_patrol",
	},
	-- Passive counterpart to the active Emergency Hull Repair below (per
	-- direct instruction: the repair pair should be one PASSIVE module that
	-- raises the hull's own repair rate and one ACTIVE module that restores
	-- hull in a burst). Always on, like the plating tiers above; `stats`
	-- names the ships.lua `data` field it boosts (hull_recovery_per_sec -
	-- 5/s on every Patrol hull). Same as every other Hull/Engine module, the
	-- bonus AMOUNT is still undecided (plan.md §2.8.11), so none is given.
	["hull_repair_booster_patrol"] = {
		name = "Hull Repair Booster",
		type = "hull",
		behavior = "passive",
		stats = { "hull_recovery_per_sec" },
		ship_class = "Patrol",
		icon = "hull_repair_booster_patrol",
	},
	-- Real confirmed capability (source wiki: "...grant in-flight hull
	-- repair ability"), distinct from the passive plating items above -
	-- an ACTIVE one-shot ability, same footing as computer_modules.lua's
	-- own Asteroid Analyser. No power_draw/wear_per_use given anywhere real -
	-- omitted rather than guessed (plan.md §4) - but per direct instruction
	-- the SHAPE of the ability is fixed: activating it restores hull points,
	-- then it goes on cooldown before it can be used again. `repair_amount`
	-- and `cooldown_s` are PLACEHOLDERS (per direct instruction: "we will
	-- add accurate details later"), marked as such like asteroids.lua's own
	-- HULL_PER_METER - not real BSGO figures.
	["emergency_hull_repair_patrol"] = {
		name = "Emergency Hull Repair",
		type = "hull",
		behavior = "active", -- no `stats`: a one-shot burst, not a passive stat change
		ship_class = "Patrol",
		icon = "emergency_hull_repair_patrol",
		repair_amount = 200, -- PLACEHOLDER: hull points restored per activation
		cooldown_s = 60, -- PLACEHOLDER: seconds before it can be used again
	},
}

return M
