-- GENERATED by tools/sync_server_rules.py from main/data/modules/weapons_launchers.lua - edit that file, not this copy.
-- Weapon (Launcher) module entries (plan.md §2.8). The second weapon
-- subtype alongside Auto Cannons: unlike a cannon, a launcher never fires
-- on its own - it launches a missile or torpedo consumed from
-- `main/data/ordinance.lua`, and carries no damage/range stats of its own
-- (that lives on the ordinance it fires).
--
-- Two subtypes, per §2.8's decision:
--   general          - a general-purpose missile launcher; fires missiles,
--                      which are broadly interchangeable across launchers.
--   nuclear_launcher - fires NUCLEAR TORPEDOES ONLY. A nuclear torpedo is
--                      restricted to this subtype and cannot be loaded into
--                      a general launcher (§2.8's compatibility rule; §2.6
--                      gates it behind Valour).
-- `launcher_type` is the local field holding this subtype, and is what an
-- ordinance entry's own `compatible_weapon` must match to be loadable -
-- "general" here pairs with `compatible_weapon = "general"` missiles, and
-- "nuclear_launcher" with the `nuclear_launcher` torpedo. Enforced by
-- data, not by separate tables per weapon (§2.8).
--
-- Naming (decided, revised - "exact reference names", per direct
-- instruction): launchers now carry the reference game's OWN published
-- designations verbatim where it has them (bsgo.fandom.com/wiki/Weapons) -
-- an ACKNOWLEDGED §0 DEVIATION, same as the combat cannons
-- (weapons_autocannons.lua's header / plan.md §0). Where the reference lists a
-- single shared name, the entry keeps one `name` and no `faction_names`;
-- where it has no launcher at all (its Line Systems page is empty), the
-- earlier original scheme is retained.
--   Patrol  general -> HD-70 "Lightning" / Type B "Bereaver"  (two names)
--           anti-capital (fills our nuclear slot) -> HD-96 "Nova" (shared;
--                      the reference's specialized anti-capital light
--                      launcher - its role is what our nuclear_launcher
--                      fills, though the reference's Nova fires missiles, not
--                      nuclear torpedoes)
--   Escort  general -> HD-M50 "Thunderbolt" (shared, reference's Medium
--                      Missile Battery)
--   Escort  nuclear -> NL-E "Sunburst" / Type NE "Annihilator" (no reference
--                      entry; original retained)
--   Frigate general -> ML-F "Downpour" / Type MF "Volley" (reference Line
--                      page empty; original retained)
--   Frigate nuclear -> NL-F "Supernova" / Type NF "Obliterator" (original
--                      retained)
-- The reference published no numeric launcher stats at all (the launcher is
-- just a mount; the numbers sit on the ammunition), so none are invented
-- here. Launchers default to the same `arc = 75` the auto cannons use
-- (§2.8), pending real per-launcher tuning (plan.md §4).
--
-- `icon`: no dedicated missile/launcher icon exists yet, so every entry
-- placeholder-shares the combat "Octagon Cannon Spaceship" region for now -
-- flagged in plan.md §4 alongside the per-variant cannon art.
--
-- No `ship_class` enforcement caveat note needed here beyond the one the
-- auto cannons carry: `ship_class` is read by the outpost screen's
-- Shop/Owned filtering (§2.8.5) but is NOT yet checked at install time
-- (plan.md §4).

local M = {}

M.LAUNCHERS = {
	-- Patrol-tier launchers.
	["missile_launcher_basic"] = {
		name = "HD-70 \"Lightning\"", -- Accord (default/reference) name, see the header's naming convention
		faction_names = { accord = "HD-70 \"Lightning\"", swarm = "Type B \"Bereaver\"" },
		type = "weapon",
		subtype = "launcher",
		launcher_type = "general", -- fires interchangeable missiles only
		behavior = "toggle", -- §2.8: weapons are always toggle-type
		ship_class = "Patrol", -- see the ship_class caveat above
		icon = "Octagon Cannon Spaceship", -- placeholder, see the icon comment above
		arc = 75,
	},
	["nuclear_launcher_basic"] = {
		name = "HD-96 \"Nova\"", -- shared name - reference's anti-capital light launcher, see the header
		type = "weapon",
		subtype = "launcher",
		launcher_type = "nuclear_launcher", -- nuclear torpedoes only (§2.8)
		behavior = "toggle",
		ship_class = "Patrol",
		icon = "Octagon Cannon Spaceship",
		arc = 75,
	},
	-- Escort-tier launchers.
	["missile_launcher_escort"] = {
		name = "HD-M50 \"Thunderbolt\"", -- shared name - reference's Medium Missile Battery
		type = "weapon",
		subtype = "launcher",
		launcher_type = "general",
		behavior = "toggle",
		ship_class = "Escort",
		icon = "Octagon Cannon Spaceship",
		arc = 75,
	},
	["nuclear_launcher_escort"] = {
		name = "NL-E \"Sunburst\"", -- no reference entry; original name retained
		faction_names = { accord = "NL-E \"Sunburst\"", swarm = "Type NE \"Annihilator\"" },
		type = "weapon",
		subtype = "launcher",
		launcher_type = "nuclear_launcher",
		behavior = "toggle",
		ship_class = "Escort",
		icon = "Octagon Cannon Spaceship",
		arc = 75,
	},
	-- Frigate-tier launchers.
	["missile_launcher_frigate"] = {
		name = "ML-F \"Downpour\"", -- no reference entry (Line page empty); original name retained
		faction_names = { accord = "ML-F \"Downpour\"", swarm = "Type MF \"Volley\"" },
		type = "weapon",
		subtype = "launcher",
		launcher_type = "general",
		behavior = "toggle",
		ship_class = "Frigate",
		icon = "Octagon Cannon Spaceship",
		arc = 75,
	},
	["nuclear_launcher_frigate"] = {
		name = "NL-F \"Supernova\"", -- no reference entry; original name retained
		faction_names = { accord = "NL-F \"Supernova\"", swarm = "Type NF \"Obliterator\"" },
		type = "weapon",
		subtype = "launcher",
		launcher_type = "nuclear_launcher",
		behavior = "toggle",
		ship_class = "Frigate",
		icon = "Octagon Cannon Spaceship",
		arc = 75,
	},
}

-- Can `launcher` (a catalog entry) fire `ordinance` (an ordinance.lua
-- entry)? Launchers carry no damage of their own, so this compatibility
-- check is the whole of their firing logic at the data layer. Matches the
-- ordinance's own `compatible_weapon` against the launcher's
-- `launcher_type` - the "enforced by data, not by separate tables per
-- weapon" rule §2.8 specifies. Returns false for a non-launcher or a
-- launcher/ordinance pair of the wrong subtype (e.g. a nuclear torpedo in
-- a general launcher).
function M.accepts(launcher, ordinance)
	if not (launcher and ordinance) then
		return false
	end
	return launcher.launcher_type ~= nil
		and ordinance.compatible_weapon == launcher.launcher_type
end

return M
