-- GENERATED by tools/sync_server_rules.py from main/session.lua - edit that file, not this copy.
-- The logged-in player's game state and the rules for changing it: faction,
-- Tope/resources, ships, modules and skins.
--
-- The SAME file runs in two places:
--   * the client (shared_state = 1 in game.project), which applies each
--     change straight away so the game feels instant, and
--   * the Nakama server (nakama-server/modules/economy.lua, via the copy
--     made by tools/sync_server_rules.py), which is the authority: it
--     re-applies each change to the saved profile and rejects anything the
--     rules don't allow. Players can't edit their balances or items.
-- So this file must stay pure Lua: no engine APIs (go/msg/gui/vmath/sys),
-- and it may only require data modules that are synced too.
--
-- Every function that changes state reports (name, args) to the on_change
-- hook after it succeeds (see the bottom of this file); main/profile.lua
-- turns that into the server call.

local skins = require("main.data.skins")
local skin_prices = require("main.data.skin_prices")
local ships = require("main.data.ships")
local star_systems = require("main.data.star_systems")
local catalog = require("main.data.modules.catalog")
local ranks = require("main.data.ranks")
local ship_class_levels = require("main.data.ship_class_levels")

local M = {}

M.faction = nil -- "accord" | "swarm" | nil (not chosen yet)
M.owned_ships = nil -- list of ship ids owned (main/data/ships.lua's M.SHIPS)
M.active_ship_id = nil -- which owned ship is currently selected/fitted
-- Set of owned ship ids that have been upgraded to their ADVANCED tier
-- (main/data/ships.lua's per-ship `advanced` component-slot table, an
-- alternative to `components` for a ship that's been upgraded) - a plain
-- { [ship_id] = true } set, not a list, since a ship is either advanced or
-- it isn't. One-way: a player upgrades their existing ship in place and
-- can't revert to the basic tier afterward (direct instruction) - there's
-- deliberately no "un-advance" function. Cleared for a ship_id on
-- M.sell_ship so a later re-purchase of that same ship starts fresh at the
-- basic tier, same as a brand-new copy would.
M.advanced_ships = nil
-- Ship skins (assets/skins/README.md): `owned_skins` is a { [skin_id] = true }
-- set of bought skins, keyed like main/data/skins.lua ("sardine.starlight").
-- `equipped_skins` maps an owned ship_id to the skin_id it wears; no entry
-- means the default faction_skins model. A skin belongs to one species, so it
-- stays owned (and equipped) if its ship is sold and bought back later.
M.owned_skins = nil
M.equipped_skins = nil
-- Flight: which system the ship is in, and a jump that's been paid for but
-- hasn't arrived (so cancelling can refund exactly what was paid). The
-- server needs these to price FTL jumps itself - see M.start_jump().
M.current_system = nil
M.pending_jump = nil -- { to = system_id, cost = hydrogen } or nil
-- Dock / launch cooldown state (§2.16, per direct instruction): `flying` is
-- true between M.launch() and the next M.dock() - the "is the ship in space"
-- flag - and `launch_blocked_until` is the earliest time a launch may leave
-- the outpost, on the SERVER's clock (see the clock hooks below). Both are
-- persisted with the profile, so the cooldown is part of the save rather than
-- of one browser session: that is the whole point of it, a reload must not
-- hand the player an instant relaunch.
M.flying = nil
M.launch_blocked_until = nil
-- Progression (main/data/ranks.lua): total XP, the systems arrived in so far
-- ({ [system_id] = true }, for first-arrival XP) and today's assignments
-- ({ date = "YYYY-MM-DD", list = { { id, progress, done } } }). Only the
-- server changes these (nakama-server/modules/progress.lua): no operation
-- below does, and they're carried through serialize()/restore() untouched so
-- the server's economy operations never drop them.
M.xp = 0
M.visited = nil
M.assignments = nil
-- `owned`: list of OWNED INSTANCES, NOT catalog type-keys — decided (§4) that
-- module upgrades are per PHYSICAL COPY, not a shared per-type "blueprint"
-- upgrade, so two owned copies of a weapon need to be distinguishable and independently
-- upgradeable. Each entry: { id = <unique instance id>, item_key = <catalog
-- key, main/data/modules/catalog.lua>, level = <int, starts at 0> }.
M.owned = nil
-- `loadout`: list of { slot = "W1"/"W2"/..., instance_id = <owned instance's
-- id> } — currently installed. Keyed by INSTANCE id (not item type key) for
-- the same reason: installing/uninstalling must track which specific
-- upgraded copy is in a slot, not just which type.
M.loadout = nil
-- NOTE: `owned`/`loadout` are a single global pool, not yet scoped per
-- ship — only one ship exists in the roster so far (§2.1.2), so there's
-- nothing to test per-ship segregation against yet. Flagged as an open
-- question in plan.md §4 once more ships exist.

-- `tope`: the player's balance of Tope (§2.6's general currency, as
-- opposed to PvP-only Valour). Per direct instruction, the outpost screen
-- always shows this and it updates as items/ships are bought and sold -
-- which needs a REAL balance and REAL transaction amounts to do
-- honestly, not just a static display. STARTING_TOPE and every price/
-- refund below are FLAT PLACEHOLDER values, not real per-item economy
-- design (§2.6's actual pricing is still open work, §4) - introduced
-- now purely so the currency display has something genuine to show and
-- update, rather than a number that never changes.
M.tope = nil
local STARTING_TOPE = 1000
local MODULE_PRICE = 100
local MODULE_SELL_REFUND = 50
-- Ship purchase prices are per ship, in main/data/ships.lua's `price`
-- (M.get_ship_price below). The sell refund is still a flat placeholder.
local SHIP_SELL_REFUND = 250
local SHIP_ADVANCE_PRICE = 500

-- `valour`: the PvP-only currency (§2.6), spent on nuclear ordinance and
-- Carrier-class ships - and, per revised-patrol-ships.csv, the upgraded
-- Tactical Patrol's price (the first ship price denominated in Valour,
-- plan.md §2.1.4). Nothing awards Valour yet (PvP rewards are unimplemented),
-- so STARTING_VALOUR is 0: the balance is tracked and checked for real, it
-- just cannot be earned or meaningfully spent until that lands. Flagged in
-- plan.md §2.6/§4.
M.valour = nil
local STARTING_VALOUR = 0

-- `water`/`iron`/`hydrogen`: the player's balances of the three RESOURCES
-- (§2.6) - distinct from Tope/Valour, which are the two CURRENCIES. Per
-- direct instruction, the outpost screen always shows all four of these
-- balances together. Water/Iron/Hydrogen can all now change for real:
-- mining an asteroid credits the depleting player its Water/Iron/Hydrogen
-- (nakama-server/modules/resources.lua, plan.md §2.11), and
-- main/player_ship.script's FTL jump (per direct instruction,
-- "implement [the SuperShips jump mechanic] here") is the first real
-- Hydrogen transaction - see M.start_jump/M.cancel_jump below,
-- mirroring M.spend_tope's own shape. STARTING_WATER/IRON/HYDROGEN are
-- flat placeholder values with no economy-balancing behind them yet (same
-- caveat as STARTING_TOPE above); note they're not even scaled against
-- the existing repair_cost_iron = 10000 placeholder stat, since nothing
-- spends against that one yet - reconciling that scale is open work,
-- plan.md §4.
M.water = nil
M.iron = nil
M.hydrogen = nil
local STARTING_WATER = 500
local STARTING_IRON = 500
local STARTING_HYDROGEN = 5000

-- Monotonically-increasing instance id counter, reset on every
-- choose_faction (a fresh guest session) — plain incrementing integers are
-- fine since this is in-memory/per-tab state, never persisted or compared
-- across sessions (§3.2).
local next_instance_id = 1
local function alloc_instance_id()
	local id = next_instance_id
	next_instance_id = next_instance_id + 1
	return id
end

-- Starting gift for every new character, regardless of faction (direct
-- instruction): the Patrol Interceptor ship (§2.1.2) fitted with one basic
-- Auto Cannon and one Mining Cannon ("Gopher", §2.8) — one in each
-- weapon slot. The Asteroid Analyser (§2.8, a Computer-slot module) is NOT
-- part of the starting gift — it's available to purchase instead (see the
-- outpost screen's Shop tab), demonstrating the owned-vs-purchasable
-- distinction below.
local STARTING_SHIP_ID = "patrol_interceptor"
local STARTING_GIFT_SLOTS = {
	{ slot = "W1", item_key = "auto_cannon_basic" },
	{ slot = "W2", item_key = "mining_cannon_basic" },
}

-- Sets the chosen faction AND assigns the starting gift in one call, so
-- there's a single place that defines "what does a new character start
-- with" rather than that logic being duplicated at each call site. Each
-- starting item is granted as its own fresh instance (id 1, 2, ... after
-- the counter reset below), same as any other purchase — no special-cased
-- data shape for starting-gift items.
local function start_character(faction)
	M.faction = faction
	M.owned_ships = { STARTING_SHIP_ID }
	M.flying = nil -- a brand-new character has nothing to cool down (§2.16)
	M.launch_blocked_until = nil
	M.active_ship_id = STARTING_SHIP_ID
	M.advanced_ships = {}
	M.owned_skins = {}
	M.equipped_skins = {}
	M.current_system = star_systems.HOME_SYSTEM[faction]
	M.pending_jump = nil
	M.xp = 0
	M.visited = { [M.current_system] = true } -- no first-arrival XP for home
	M.assignments = nil
	next_instance_id = 1
	M.owned = {}
	M.loadout = {}
	M.tope = STARTING_TOPE
	M.valour = STARTING_VALOUR
	M.water = STARTING_WATER
	M.iron = STARTING_IRON
	M.hydrogen = STARTING_HYDROGEN
	for _, gift in ipairs(STARTING_GIFT_SLOTS) do
		local id = alloc_instance_id()
		table.insert(M.owned, { id = id, item_key = gift.item_key, level = 0 })
		table.insert(M.loadout, { slot = gift.slot, instance_id = id })
	end
end

-- A new player's one-time faction choice. The server only accepts it for a
-- profile that has no faction yet (nakama-server/modules/economy.lua).
function M.choose_faction(faction)
	start_character(faction)
end

function M.get_xp()
	return M.xp or 0
end

function M.get_level()
	return ranks.level_for_xp(M.xp)
end

function M.get_rank()
	return ranks.rank_name(M.faction, M.get_level())
end

-- Today's assignments as saved by the server, or nil before any progress.
function M.get_assignments()
	return M.assignments
end

-- The stat block in effect for `ship_id`: the basic tier's `data`, overlaid
-- with the advanced tier's own `data` once the ship has been upgraded
-- (main/data/ships.lua's `basic`/`advanced` sections). The advanced section
-- only lists the fields that actually change, so anything it leaves unset
-- falls back to basic - the whole point of splitting the two tiers this way.
function M.get_ship_data(ship_id)
	local ship = ships.SHIPS[ship_id]
	if not ship then
		return nil
	end
	local basic_data = (ship.basic and ship.basic.data) or {}
	if not (M.is_ship_advanced(ship_id) and ship.advanced and ship.advanced.data) then
		return basic_data
	end
	local merged = {}
	for field, value in pairs(basic_data) do
		merged[field] = value
	end
	for field, value in pairs(ship.advanced.data) do
		merged[field] = value
	end
	return merged
end

-- A single stat of `ship_id`, by the same basic/advanced fallback rule as
-- get_ship_data above - but without building a merged table, because this is
-- the one the flight-time callers use (sensor range, FTL range/cost, flight
-- stats), several of them every frame.
function M.ship_stat(ship_id, field)
	local ship = ships.SHIPS[ship_id]
	if not ship then
		return nil
	end
	if M.is_ship_advanced(ship_id) and ship.advanced and ship.advanced.data then
		local value = ship.advanced.data[field]
		if value ~= nil then
			return value
		end
	end
	return ship.basic and ship.basic.data and ship.basic.data[field]
end

-- Slot counts in effect for `ship_id`: its advanced tier's once upgraded,
-- otherwise its normal `components` (main/data/ships.lua's `basic`/
-- `advanced` sections).
function M.get_components(ship_id)
	local ship = ships.SHIPS[ship_id]
	if not ship then
		return {}
	end
	if M.is_ship_advanced(ship_id) and ship.advanced then
		return ship.advanced.components or (ship.basic and ship.basic.components) or {}
	end
	return (ship.basic and ship.basic.components) or {}
end

-- Hotkeys (per direct instruction, fixed per slot): weapon slot Wn is
-- Shift+n; Computer, Engine and Hull slots share 1-9, numbered C1.., then
-- E1.., then H1.. across the active ship's slots. Only numbers 1-9 are
-- keys; slots past 9 have none.
M.MODULE_HOTKEY_ORDER = { "C", "E", "H" }

-- The hotkey number for `slot` ("W2" -> 2, "E1" -> 3 on a ship with two
-- Computer slots), or nil.
function M.slot_hotkey(ship_id, slot)
	local prefix, number = tostring(slot):match("^(%a)(%d+)$")
	number = tonumber(number)
	if not number then
		return nil
	end
	if prefix == "W" then
		return number <= 9 and number or nil
	end
	local counts = M.get_components(ship_id)
	local offset = 0
	for _, kind in ipairs(M.MODULE_HOTKEY_ORDER) do
		if kind == prefix then
			local key = offset + number
			return key <= 9 and key or nil
		end
		offset = offset + (counts[kind] or 0)
	end
	return nil
end

-- The Computer/Engine/Hull slot that key `n` (1-9) belongs to, or nil.
function M.module_slot_for_hotkey(ship_id, n)
	local counts = M.get_components(ship_id)
	local offset = 0
	for _, kind in ipairs(M.MODULE_HOTKEY_ORDER) do
		local count = counts[kind] or 0
		if n > offset and n <= offset + count then
			return kind .. (n - offset)
		end
		offset = offset + count
	end
	return nil
end

-- The catalog entry of the module fitted in `slot` (main/data/modules/
-- catalog.lua) and its instance, or nil.
function M.module_in_slot(slot)
	for _, entry in ipairs(M.loadout or {}) do
		if entry.slot == slot then
			local instance = M.get_instance(entry.instance_id)
			return instance and catalog.get(instance.item_key), instance
		end
	end
	return nil
end

-- Level needed to buy `ship_id` (main/data/ship_class_levels.lua), 1 if its
-- class has no requirement.
function M.ship_level_required(ship_id)
	local ship = ships.SHIPS[ship_id]
	return ship and ship_class_levels.LEVELS[ship.class] or 1
end

function M.get_faction()
	return M.faction
end

function M.get_tope()
	return M.tope
end

function M.get_valour()
	return M.valour
end

function M.get_water()
	return M.water
end

function M.get_iron()
	return M.iron
end

function M.get_hydrogen()
	return M.hydrogen
end

-- Hydrogen is only ever spent on FTL jumps, priced by these functions from
-- the saved current system - never an amount the caller supplies - so the
-- server can check every jump (main/player_ship.script calls them).
local DEFAULT_FTL_RANGE_LY = 4.5 -- same fallback as main/player_ship.script's flight_stats()
local DEFAULT_FTL_COST_PER_LY = 30 -- the class baseline in main/data/ships.lua

-- Hydrogen per light-year jumped by `ship_id` (its FTL Cost stat).
function M.ftl_cost_per_ly(ship_id)
	return M.ship_stat(ship_id, "ftl_cost_hydrogen_per_ly") or DEFAULT_FTL_COST_PER_LY
end

-- The system whose outpost the player is at whenever they're not flying:
-- their current system if their faction has an outpost there, otherwise
-- their home system. That covers docking (only possible at an outpost),
-- quitting mid-flight, and being destroyed: in a system without one of
-- their outposts, they're back at home.
function M.docked_system()
	if M.current_system and M.outpost_available(M.current_system, M.faction) then
		return M.current_system
	end
	return star_systems.HOME_SYSTEM[M.faction]
end

-- Is `faction`'s outpost in `system_id` there right now? By default just
-- "does the faction have an outpost in that system" (star_systems). Outposts
-- can also be destroyed for an hour, which only the server knows for sure:
-- nakama-server/modules/economy.lua replaces this with the live state, and
-- the game with its latest copy of it (main/network.lua). A destroyed outpost
-- counts as no outpost - docking, quitting and respawning there send the
-- player home.
local outpost_available_fn = nil
function M.set_outpost_availability(fn)
	outpost_available_fn = fn
end

function M.outpost_available(system_id, faction)
	if not star_systems.has_outpost(system_id, faction) then
		return false
	end
	if outpost_available_fn then
		return outpost_available_fn(system_id, faction)
	end
	return true
end

-- ---------------------------------------------------------------------------
-- Dock / launch cooldown (§2.16, per direct instruction)
-- ---------------------------------------------------------------------------

-- Seconds before a launch may leave the outpost, counted from the moment the
-- ship docked - or, being destroyed, was returned to one. Both go through
-- main/player_ship.script's complete_dock(), which calls M.dock() below, so
-- the two cases are deliberately the same length.
local DOCK_LAUNCH_COOLDOWN = 10

-- Seconds before a launch may leave the outpost when the previous session
-- ended IN SPACE instead of docking: the player reloaded the browser, closed
-- the tab, or quit mid-flight. M.resume() applies it. Deliberately only that
-- case (decided): a page load while already docked keeps whatever is left of
-- the ordinary dock cooldown, which the profile already carries - the longer
-- one is for ending the game rather than docking it.
local SESSION_END_LAUNCH_COOLDOWN = 60

-- The host's own clock, in seconds since the Unix epoch. A hook rather than a
-- direct os.time() call for the same reason M.set_outpost_availability exists
-- above: the tests drive both cooldowns with a clock they control instead of
-- waiting. os.time is standard Lua (not an engine API), so both hosts still
-- work unconfigured, and nakama-server/modules/economy.lua sets it to the
-- server's own nk.time() so the server's timestamps are the authoritative
-- ones.
local clock = os.time
function M.set_clock(fn)
	clock = fn or os.time
end

-- The host clock's offset from the SERVER's clock, in seconds. The cooldown
-- timestamps live in the saved profile, which only the server writes, so the
-- game has to read and write them on the server's clock - never the local one,
-- which a player can simply change. M.sync_clock() sets this from any reply
-- carrying the server's own time (nakama-server/modules/economy.lua's `now`,
-- in milliseconds); until one arrives the offset is 0, which is close enough
-- because both clocks are Unix times.
local clock_offset = 0
function M.sync_clock(server_ms)
	if server_ms then
		clock_offset = server_ms / 1000 - clock()
	end
end

-- The SERVER's clock in seconds - what every cooldown timestamp is stored in.
local function server_now()
	return clock() + clock_offset
end

-- Seconds until the player may launch again; 0 while no cooldown is running.
-- The outpost screen (main/outpost.gui_script) gates its Launch button on
-- this, and the server re-checks it through M.launch() below.
function M.launch_cooldown_left()
	if not M.launch_blocked_until then
		return 0
	end
	return math.max(0, M.launch_blocked_until - server_now())
end

-- Is the ship out in space right now (as opposed to docked at an outpost)?
function M.is_flying()
	return M.flying and true or false
end

-- Takes off from the outpost the player is at (M.docked_system()). A jump
-- that was paid for but never arrived (the game was closed mid-countdown)
-- is refunded. Refused - and nothing at all changes - while the dock cooldown
-- is still running (§2.16), or while the ship is already in space: docking is
-- the only thing that clears M.flying, and docking is exactly what arms the
-- cooldown, so this is what makes the cooldown impossible to skip by simply
-- never reporting the dock. Callers stay docked (main/player_ship.script's
-- start_flight() puts the outpost screen back up).
function M.launch()
	if M.flying or M.launch_cooldown_left() > 0 then
		return false
	end
	if M.pending_jump then
		M.hydrogen = M.hydrogen + M.pending_jump.cost
		M.pending_jump = nil
	end
	M.current_system = M.docked_system()
	M.flying = true
	return true
end

-- The ship is docked at an outpost again: either a completed docking
-- (main/player_ship.script's docking countdown) or being destroyed and
-- respawning at one (its ship_destroyed()) - both route through complete_dock(),
-- which is where this is called from. Clears M.flying (so a launch is allowed
-- again) and starts the ordinary dock cooldown. Never SHORTENS a cooldown
-- already running, so a dock during the long session-end one cannot cut it
-- back down to ten seconds.
function M.dock()
	M.flying = false
	M.launch_blocked_until = math.max(M.launch_blocked_until or 0, server_now() + DOCK_LAUNCH_COOLDOWN)
	return true
end

-- A returning player's session begins at an outpost: main/profile.lua calls
-- this once the saved profile has been loaded (and only for a profile that
-- already has a faction). If that profile still says the ship was IN SPACE when
-- the last session ended - the game was reloaded, closed or quit mid-flight -
-- ending the game must not be a free relaunch, so the much longer session-end
-- cooldown replaces the dock one (per direct instruction: 60 seconds). A
-- session that ended docked arms nothing new: whatever is left of the dock
-- cooldown is already in the profile.
function M.resume()
	local was_flying = M.flying and true or false
	M.flying = false -- at the outpost from here on, whoever ends the session next
	if was_flying then
		M.launch_blocked_until = math.max(M.launch_blocked_until or 0, server_now() + SESSION_END_LAUNCH_COOLDOWN)
	end
	return true
end

-- The system whose outpost the player is at (or last launched from).
function M.get_current_system()
	return M.current_system
end

-- Hydrogen cost of jumping from the current system to `system_id` with the
-- active ship, or nil if that jump isn't allowed (unknown/hostile system,
-- out of FTL range, already jumping).
function M.jump_cost(system_id)
	if M.pending_jump or not M.current_system or system_id == M.current_system then
		return nil
	end
	if not star_systems.can_enter(system_id, M.faction) then
		return nil
	end
	local range_ly = M.ship_stat(M.active_ship_id, "ftl_range_ly") or DEFAULT_FTL_RANGE_LY
	local distance = star_systems.distance(M.current_system, system_id)
	if not star_systems.in_ftl_range(distance, star_systems.ly_to_map_units(range_ly)) then
		return nil
	end
	return star_systems.hydrogen_cost(distance, M.ftl_cost_per_ly(M.active_ship_id))
end

-- Pays for a jump to `system_id`. Returns the cost, or nil if the jump isn't
-- allowed or affordable (nothing is spent).
function M.start_jump(system_id)
	local cost = M.jump_cost(system_id)
	if not cost or M.hydrogen < cost then
		return nil
	end
	M.hydrogen = M.hydrogen - cost
	M.pending_jump = { to = system_id, cost = cost }
	return cost
end

-- Cancels the jump in progress, refunding its Hydrogen.
function M.cancel_jump()
	if not M.pending_jump then
		return false
	end
	M.hydrogen = M.hydrogen + M.pending_jump.cost
	M.pending_jump = nil
	return true
end

-- The jump in progress lands: the ship is now in its target system.
function M.arrive_jump()
	if not M.pending_jump then
		return false
	end
	M.current_system = M.pending_jump.to
	M.pending_jump = nil
	return true
end

-- The flat placeholder price/refund a caller (e.g. the outpost screen's
-- confirmation dialogs and Shop/For Sale card labels) should show and
-- charge for a given kind of transaction — see the STARTING_TOPE
-- comment above on why these are placeholders, not real prices.
function M.get_module_price()
	return MODULE_PRICE
end

function M.get_module_sell_refund()
	return MODULE_SELL_REFUND
end

-- Purchase price of `ship_id`: an ordered list of { amount, currency }
-- entries - one per currency the purchase demands, so a ship can require
-- more than one currency at once (main/data/ships.lua's own header) - or
-- nil for a ship that isn't for sale (the starter ship). Callers test
-- affordability with M.can_afford and pay with M.spend_price rather than
-- reading a single amount/currency.
function M.get_ship_price(ship_id)
	local ship = ships.SHIPS[ship_id]
	return (ship and ship.basic and ship.basic.price) or nil
end

-- The balance a price in `currency` is paid from.
function M.get_balance(currency)
	if currency == "hydrogen" then
		return M.hydrogen
	elseif currency == "valour" then
		return M.valour
	end
	return M.tope
end

function M.get_ship_sell_refund()
	return SHIP_SELL_REFUND
end

-- The upgrade price of `ship_id` (main/data/ships.lua's `advanced.price`):
-- an ordered list of { amount, currency } entries, same shape as
-- M.get_ship_price above. Charged ON TOP of whatever the basic ship already
-- cost - no refund of that basic price (direct instruction). Falls back to
-- the flat SHIP_ADVANCE_PRICE placeholder (as a one-entry list) for a ship
-- whose advanced tier has no price of its own yet.
function M.get_ship_advance_price(ship_id)
	local ship = ship_id and ships.SHIPS[ship_id]
	local price = ship and ship.advanced and ship.advanced.price
	if not price then
		return { { amount = SHIP_ADVANCE_PRICE, currency = "tope" } }
	end
	return price
end

-- Spends `amount` Tope if (and only if) the player can afford it —
-- returns false and changes nothing otherwise. The balance never goes
-- negative.
local function spend_tope(amount)
	if M.tope < amount then
		return false
	end
	M.tope = M.tope - amount
	return true
end

-- Spends `amount` of `currency` ("tope", "hydrogen" or "valour") if (and
-- only if) the player can afford it - returns false and changes nothing
-- otherwise. Anything that isn't one of those three falls through to Tope,
-- same as before this gained a Valour branch (every price in
-- main/data/ships.lua names a real currency, so that path is unreachable in
-- practice).
local function spend(amount, currency)
	if currency == "hydrogen" then
		if M.hydrogen < amount then
			return false
		end
		M.hydrogen = M.hydrogen - amount
		return true
	elseif currency == "valour" then
		if (M.valour or 0) < amount then
			return false
		end
		M.valour = (M.valour or 0) - amount
		return true
	end
	return spend_tope(amount)
end

local function add_tope(amount)
	M.tope = M.tope + amount
end

-- Can the player pay EVERY entry in `price` (an ordered { amount, currency }
-- list, main/data/ships.lua)? False as soon as any one currency is short -
-- a multi-currency price is all-or-nothing, never partially paid.
function M.can_afford(price)
	for _, part in ipairs(price or {}) do
		if (M.get_balance(part.currency) or 0) < part.amount then
			return false
		end
	end
	return true
end

-- Pays every entry in `price` at once (all-or-nothing): spends nothing and
-- returns false if any entry is unaffordable, otherwise deducts every entry
-- and returns true. `spend` above is the single-currency primitive.
function M.spend_price(price)
	if not M.can_afford(price) then
		return false
	end
	for _, part in ipairs(price) do
		spend(part.amount, part.currency)
	end
	return true
end

-- Kept as the existing accessor name (used throughout the outpost
-- screen already) - now returns the currently SELECTED owned ship,
-- rather than there only ever being one possible ship.
function M.get_ship_id()
	return M.active_ship_id
end

function M.get_owned_ships()
	return M.owned_ships
end

-- Does the player own `ship_id` at all?
function M.is_ship_owned(ship_id)
	for _, id in ipairs(M.owned_ships or {}) do
		if id == ship_id then
			return true
		end
	end
	return false
end

-- Has `ship_id` been upgraded to its advanced tier? False for a ship not
-- even owned, same as every other per-ship query here.
function M.is_ship_advanced(ship_id)
	return M.advanced_ships[ship_id] == true
end

-- Upgrades an OWNED ship to its advanced tier in place - one-way (direct
-- instruction: "once a ship has been advanced it cannot be returned back
-- to the basic model"), so there's no M.revert_ship counterpart. Refuses
-- (returns false, spending nothing) if the ship isn't owned, is already
-- advanced, or the player can't afford it. Spends that ship's own
-- advanced-tier price (get_ship_advance_price, main/data/
-- ships.lua), in whatever currency it names. Deliberately does NOT check
-- whether main/data/ships.lua even has an `advanced` table for this ship_id
-- - same division of responsibility as every other session function here
-- (M.purchase_ship doesn't check ships.SHIPS either): session.lua tracks
-- state by id only, the outpost screen (which already `require`s ships.lua)
-- is what decides whether the Advance option is even offered for a ship.
function M.advance_ship(ship_id)
	if not M.is_ship_owned(ship_id) then
		return false
	end
	if not (ships.SHIPS[ship_id] and ships.SHIPS[ship_id].advanced) then
		return false -- this ship has no advanced tier
	end
	if M.is_ship_advanced(ship_id) then
		return false
	end
	local price = M.get_ship_advance_price(ship_id)
	if not M.spend_price(price) then
		return false
	end
	M.advanced_ships[ship_id] = true
	return true
end

-- Switches the active ship to `ship_id`, if owned. No-op otherwise.
function M.select_ship(ship_id)
	if M.is_ship_owned(ship_id) then
		M.active_ship_id = ship_id
		return true
	end
	return false
end

-- Adds `ship_id` to owned ships if not already owned, paying its
-- get_ship_price() - every currency the price names, all at once (a
-- multi-currency price is all-or-nothing). Returns false, spending nothing,
-- if the ship isn't for sale, is already owned, or the player can't afford
-- the whole price.
function M.purchase_ship(ship_id)
	local price = M.get_ship_price(ship_id)
	if not price or M.is_ship_owned(ship_id) then
		return false
	end
	if M.get_level() < M.ship_level_required(ship_id) then
		return false
	end
	if not M.spend_price(price) then
		return false
	end
	table.insert(M.owned_ships, ship_id)
	return true
end

-- Tope price of `skin_id`, from its collection (main/data/skin_prices.lua),
-- or nil for an unknown skin.
function M.get_skin_price(skin_id)
	local skin = skins.SKINS[skin_id]
	return skin and skin_prices.PRICES[skin.collection]
end

function M.is_skin_owned(skin_id)
	return M.owned_skins[skin_id] == true
end

-- Buys `skin_id` for get_skin_price(skin_id) Tope. Returns false, spending
-- nothing, for an unknown or already-owned skin or if the player can't
-- afford it.
function M.purchase_skin(skin_id)
	local price = M.get_skin_price(skin_id)
	if not price or M.is_skin_owned(skin_id) then
		return false
	end
	if not spend_tope(price) then
		return false
	end
	M.owned_skins[skin_id] = true
	return true
end

-- The skin_id `ship_id` currently wears, or nil for its default model.
function M.get_equipped_skin(ship_id)
	return M.equipped_skins[ship_id]
end

-- Puts owned `skin_id` on owned `ship_id`, or restores the default model when
-- `skin_id` is nil. The skin must be for this ship's chassis in the player's
-- faction. Returns false and changes nothing otherwise.
function M.equip_skin(ship_id, skin_id)
	if not M.is_ship_owned(ship_id) then
		return false
	end
	if skin_id ~= nil then
		local skin = skins.SKINS[skin_id]
		if not (skin and M.is_skin_owned(skin_id) and skin.chassis == ship_id and skin.faction == M.faction) then
			return false
		end
	end
	M.equipped_skins[ship_id] = skin_id
	return true
end

-- Returns the list of owned INSTANCES (see M.owned's own comment above) —
-- NOT catalog keys. Callers that need "do I own any copy of this type at
-- all" should use M.is_owned(item_key) instead of scanning this
-- themselves.
function M.get_owned()
	return M.owned
end

function M.get_loadout()
	return M.loadout
end

-- Looks up one owned instance by its id, or nil if no such instance
-- exists (e.g. already sold/removed — not a currently reachable case, but
-- callers should still handle it rather than assume).
function M.get_instance(instance_id)
	for _, inst in ipairs(M.owned or {}) do
		if inst.id == instance_id then
			return inst
		end
	end
	return nil
end

-- Is this SPECIFIC owned instance currently installed in any slot? Takes
-- an instance id, NOT a catalog item key — two owned copies of the same
-- module type can have different install states (and different upgrade
-- levels, M.upgrade below). Use M.is_type_installed for the "is ANY copy
-- of this type installed anywhere" query instead.
function M.is_installed(instance_id)
	for _, entry in ipairs(M.loadout or {}) do
		if entry.instance_id == instance_id then
			return true
		end
	end
	return false
end

-- Does the player own at least one instance of `item_key` (installed or
-- spare)? A "by type" convenience query — doesn't distinguish which
-- specific copy, or how many.
function M.is_owned(item_key)
	for _, inst in ipairs(M.owned or {}) do
		if inst.item_key == item_key then
			return true
		end
	end
	return false
end

-- Is any owned instance of `item_key` currently installed in any slot?
-- Same "by type, not by specific copy" convenience as M.is_owned.
function M.is_type_installed(item_key)
	for _, entry in ipairs(M.loadout or {}) do
		local inst = M.get_instance(entry.instance_id)
		if inst and inst.item_key == item_key then
			return true
		end
	end
	return false
end

-- Grants a brand-new OWNED INSTANCE of `item_key` — decided (§4): every
-- purchase creates its own separately-upgradeable physical copy, never
-- tops up a shared per-type count. Spends get_module_price() Tope (a
-- flat placeholder, see STARTING_TOPE's comment - not real per-item
-- pricing). Returns the new instance's id on success, so a caller (e.g.
-- the outpost screen's "drag a Shop card onto a slot" flow) can install
-- it immediately without a second lookup - or nil if the player can't
-- afford it, spending nothing.
function M.purchase(item_key)
	if not catalog.get(item_key) then
		return nil -- not a real module
	end
	if not spend_tope(MODULE_PRICE) then
		return nil
	end
	local id = alloc_instance_id()
	table.insert(M.owned, { id = id, item_key = item_key, level = 0 })
	return id
end

-- Upgrades one owned instance by a level. No cost/effect wired up yet —
-- real upgrade cost (Tope? materials?) and what a level actually changes
-- (stats, per §2.8) are both still undesigned (plan.md §4); this just
-- moves the counter so the "does an upgrade survive uninstall/reinstall"
-- mechanic (the reason this per-instance model exists at all) is real and
-- testable. No-op (returns false) if the instance doesn't exist.
function M.upgrade(instance_id)
	local inst = M.get_instance(instance_id)
	if not inst then
		return false
	end
	inst.level = inst.level + 1
	return true
end

-- Installs `instance_id` into `slot`, used by the outpost screen's
-- drag-and-drop fitting UI (§2.8/§2.9). Whatever was previously in
-- `slot` simply becomes an uninstalled spare again (still owned, just no
-- longer in a slot) — this is NOT a true two-way swap with the dragged
-- item's own origin slot, just the simplest data-consistent behavior; see
-- plan.md §4. No-op if the instance isn't owned. Since `owned` entries are
-- never mutated by install/uninstall (only `loadout` membership changes),
-- an instance's `level` is untouched by any of this — moving a fitted weapon
-- between slots, or back out to being a spare, always preserves its
-- upgrade level, which is the whole point of tracking instances instead
-- of just type keys.
function M.install(slot, instance_id)
	if not M.get_instance(instance_id) or not M.slot_exists(slot) then
		return false
	end
	-- pull this instance out of whatever slot it's currently in, if any
	for i, entry in ipairs(M.loadout) do
		if entry.instance_id == instance_id then
			table.remove(M.loadout, i)
			break
		end
	end
	-- whatever currently occupies `slot` is displaced back to being a spare
	for i, entry in ipairs(M.loadout) do
		if entry.slot == slot then
			table.remove(M.loadout, i)
			break
		end
	end
	table.insert(M.loadout, { slot = slot, instance_id = instance_id })
	return true
end

-- Slot counts in effect for the active ship - just get_components above
-- (its advanced tier's once advanced, otherwise its basic `components`),
-- so this can never drift from what the outpost screen shows.
local function active_slot_counts()
	return M.get_components(M.active_ship_id)
end

-- Is `slot` (e.g. "W2") a real, usable slot on the active ship?
function M.slot_exists(slot)
	local prefix, number = tostring(slot):match("^([WCEH])(%d+)$")
	local count = prefix and active_slot_counts()[prefix]
	return count ~= nil and tonumber(number) >= 1 and tonumber(number) <= count
end

-- Removes whatever's installed in `slot`, if anything — the instance
-- stays owned (at its current upgrade level, untouched), just no longer
-- installed.
function M.uninstall(slot)
	for i, entry in ipairs(M.loadout) do
		if entry.slot == slot then
			table.remove(M.loadout, i)
			return true
		end
	end
	return false
end

-- Sells one owned module INSTANCE, per direct instruction ("there needs
-- to be an option to sell a component"). Uninstalls it first if it's
-- currently fitted somewhere (selling an equipped item unequips it,
-- rather than leaving a dangling loadout entry pointing at a
-- now-nonexistent instance), then removes it from `owned` entirely -
-- unlike M.uninstall, the instance itself stops existing, not just its
-- slot membership. Credits get_module_sell_refund() Tope (a flat
-- placeholder, see STARTING_TOPE's comment). Returns false if the
-- instance doesn't exist.
function M.sell(instance_id)
	if not M.get_instance(instance_id) then
		return false
	end
	for i, entry in ipairs(M.loadout) do
		if entry.instance_id == instance_id then
			table.remove(M.loadout, i)
			break
		end
	end
	for i, inst in ipairs(M.owned) do
		if inst.id == instance_id then
			table.remove(M.owned, i)
			break
		end
	end
	add_tope(MODULE_SELL_REFUND)
	return true
end

-- Sells an owned SHIP, per direct instruction - with the explicit
-- constraint that direct instruction also gave: "you cannot sell all
-- ships." Refuses (returns false, no-op) if `ship_id` isn't owned, or if
-- it's the player's ONLY owned ship - a player must always have at least
-- one ship. Selling the currently ACTIVE ship (while others remain) is
-- allowed - the active ship just becomes whichever other owned ship
-- happens to be first in the list afterward, so there's always a valid
-- active ship. Credits get_ship_sell_refund() Tope (a flat placeholder,
-- see STARTING_TOPE's comment).
function M.sell_ship(ship_id)
	if not M.is_ship_owned(ship_id) then
		return false
	end
	if #M.owned_ships <= 1 then
		return false
	end
	for i, id in ipairs(M.owned_ships) do
		if id == ship_id then
			table.remove(M.owned_ships, i)
			break
		end
	end
	if M.active_ship_id == ship_id then
		M.active_ship_id = M.owned_ships[1]
	end
	M.advanced_ships[ship_id] = nil
	add_tope(SHIP_SELL_REFUND)
	return true
end

-- Everything that makes up a player's saved progress, as plain data
-- (main/profile.lua stores it as JSON in Nakama storage).
function M.serialize()
	return {
		version = 1,
		faction = M.faction,
		owned_ships = M.owned_ships,
		active_ship_id = M.active_ship_id,
		advanced_ships = M.advanced_ships,
		owned = M.owned,
		loadout = M.loadout,
		next_instance_id = next_instance_id,
		tope = M.tope,
		valour = M.valour,
		water = M.water,
		iron = M.iron,
		hydrogen = M.hydrogen,
		owned_skins = M.owned_skins,
		equipped_skins = M.equipped_skins,
		current_system = M.current_system,
		pending_jump = M.pending_jump,
		flying = M.flying,
		launch_blocked_until = M.launch_blocked_until,
		xp = M.xp,
		visited = M.visited,
		assignments = M.assignments,
	}
end

-- Loads saved progress (from M.serialize()). Missing fields fall back to a
-- new character's starting values, so older saves keep working as fields
-- are added.
function M.restore(data)
	start_character(data.faction) -- starting state; saved fields below replace it
	M.owned_ships = data.owned_ships or M.owned_ships
	M.active_ship_id = data.active_ship_id or M.active_ship_id
	M.advanced_ships = data.advanced_ships or {}
	M.owned = data.owned or M.owned
	M.loadout = data.loadout or M.loadout
	next_instance_id = data.next_instance_id or next_instance_id
	M.tope = data.tope or M.tope
	M.valour = data.valour or M.valour
	M.water = data.water or M.water
	M.iron = data.iron or M.iron
	M.hydrogen = data.hydrogen or M.hydrogen
	M.owned_skins = data.owned_skins or {}
	M.equipped_skins = data.equipped_skins or {}
	M.current_system = data.current_system or M.current_system
	M.pending_jump = data.pending_jump
	M.flying = data.flying or nil
	M.launch_blocked_until = data.launch_blocked_until or nil
	M.xp = data.xp or 0
	M.visited = data.visited or M.visited
	M.assignments = data.assignments
end

-- Clears everything (logging out).
function M.reset()
	M.faction, M.owned_ships, M.active_ship_id, M.advanced_ships = nil, nil, nil, nil
	M.owned, M.loadout, M.owned_skins, M.equipped_skins = nil, nil, nil, nil
	M.tope, M.valour, M.water, M.iron, M.hydrogen = nil, nil, nil, nil, nil
	M.current_system, M.pending_jump = nil, nil
	M.flying, M.launch_blocked_until = nil, nil
	M.xp, M.visited, M.assignments = 0, nil, nil
	next_instance_id = 1
end

-- Change hook: main/profile.lua sets this to send each change to the server.
local on_change = nil
function M.set_on_change(fn)
	on_change = fn
end

-- Every function that changes saved state - and only these - can be
-- requested from the server (nakama-server/modules/economy.lua checks the
-- op name against M.OPS). Each reports on_change(name, args) after it
-- succeeds (anything but a false/nil result; choose_faction returns
-- nothing). Wrapped here in one place rather than in each function, so a
-- new rule only needs adding to this list.
M.OPS = {
	"choose_faction", "launch", "dock", "resume", "start_jump", "cancel_jump", "arrive_jump",
	"advance_ship", "select_ship", "purchase_ship", "sell_ship",
	"purchase_skin", "equip_skin",
	"purchase", "upgrade", "install", "uninstall", "sell",
}
local ALWAYS_SUCCEEDS = { choose_faction = true }
for _, name in ipairs(M.OPS) do
	local original = assert(M[name], name)
	M[name] = function(...)
		local result = original(...)
		if (result or ALWAYS_SUCCEEDS[name]) and on_change then
			on_change(name, { ... })
		end
		return result
	end
end

return M
