"""Display common-camera fleet renders with measured class dimensions."""
import html
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
rows=json.loads((ROOT/'artifacts/fleet/manifest.json').read_text())['ships']
cards=[]
for faction in ('accord','swarm'):
    for role in ('interceptor','support','assault','tactical'):
        ships=[next(r for r in rows if r['faction']==faction and r['role']==role and r['class']==size) for size in ('patrol','escort','frigate')]
        labels=''.join(f'<div><small>{r["class"].upper()} · {ratio}×</small><h3>{html.escape(r["name"])}</h3><span>{max(r["dimensions_m"]):g} m</span></div>' for r,ratio in zip(ships,(1,4,16)))
        cards.append(f'<section data-faction="{faction}"><h2>{"Accord fish" if faction=="accord" else "Swarm birds"} / {role.title()}</h2><div class="labels">{labels}</div><a href="{faction}-{role}.png"><img src="{faction}-{role}.png" loading="lazy" alt="{faction} {role}: Patrol, Escort and Frigate at the same world scale"></a></section>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Galaxy · Actual fleet sizes</title>
<style>:root{color-scheme:dark;font:16px/1.5 system-ui,sans-serif;background:#101923;color:#e5edf0}*{box-sizing:border-box}body{max-width:1400px;margin:auto;padding:36px}header{max-width:880px;margin-bottom:28px}h1{font-size:clamp(32px,5vw,62px);line-height:1.08;margin:14px 0}p{color:#b6c7d0}a{color:#b7e9de}button{background:#203640;color:#e5f5f0;border:1px solid #55726d;border-radius:8px;padding:10px 20px;font:inherit;margin-right:8px}button[aria-pressed=true]{background:#39655b}section{background:#1a2833;border:1px solid #38515b;border-radius:14px;overflow:hidden;margin:30px 0}section[hidden]{display:none}h2{font-size:20px;margin:20px 26px}.labels{display:grid;grid-template-columns:1fr 1fr 1fr;text-align:center;padding:12px 4%}.labels h3{margin:3px;font-size:clamp(14px,2vw,22px)}small{color:#9acdbf;font-size:11px}.labels span{font-weight:650}img{width:100%;display:block}footer{color:#acbec7;font-size:14px;margin:30px 0}button:focus-visible,a:focus-visible{outline:3px solid #d7b55b;outline-offset:3px}@media(max-width:600px){body{padding:16px}h2{font-size:17px}.labels{padding:8px 2%}small{font-size:9px}}</style>
<header><small>GALAXY / ACTUAL WORLD SCALE</small><h1>Small. Medium. Big.<br>1 → 4 → 16.</h1><p>Patrols keep their original size. Each Escort is four times its corresponding Patrol; each Frigate is four times its Escort. Measured by the longest dimension, with the entire ship scaled uniformly.</p><p>Every row uses one shared camera and native model sizes. The small ships really are that small beside the large ships. The regular detail galleries enlarge each ship separately.</p><nav aria-label="Faction"><button data-filter="all" aria-pressed="true">All ships</button><button data-filter="accord" aria-pressed="false">Fish</button><button data-filter="swarm" aria-pressed="false">Birds</button></nav></header>'''+''.join(cards)+'''
<footer><p>All 24 base ships and 288 cosmetic models checked. Patrol resources remain unchanged; larger ships retain their shapes, textures and topology. The Moray also has the requested straight, symmetrical hull.</p><p><a href="../themes/index.html">Theme detail gallery</a> · <a href="../cosmetics/index.html">Earlier cosmetics</a> · <a href="../moray/perspective.jpg">Moray variants</a> · <a href="validation.json">Scale validation</a> · <a href="README.md">Verification notes</a></p><p>These renders use the shipped GLBs. Defold runtime and live multiplayer still need an in-game check.</p></footer>
<script>for(const b of document.querySelectorAll('button'))b.addEventListener('click',()=>{for(const x of document.querySelectorAll('button'))x.setAttribute('aria-pressed',String(x===b));for(const s of document.querySelectorAll('section'))s.hidden=b.dataset.filter!=='all'&&s.dataset.faction!==b.dataset.filter;});</script></html>'''
(ROOT/'artifacts/scale/index.html').write_text(page,encoding='utf-8',newline='\n')
print('Built actual-scale gallery for all eight faction/role trios.')
