#!/usr/bin/env python3
"""Index the skin libraries for the game.

Reads the per-library catalogs in assets/skins/catalogs/ and writes:
  assets/skins/catalog.json               merged manifest, one entry per skin
  assets/skins/<ship>/<collection>/ship.go  factory prototype per skin
  main/skin_hub.go                        one dynamically loaded factory per skin
  main/data/skins.lua                     skin id -> ship, chassis, model, factory
  main/data/skin_collections.lua          collection id -> name, description
  main/images/skins/<ship>-<collection>.jpg  outpost Skins tab thumbnails
  main/images/skins/<ship>-default.jpg       (plus the default hull), from
                                          the review renders in artifacts/

Run after build_cosmetic_library.py or build_theme_library.py. Output is
deterministic so it can be checked in.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKINS = ROOT / 'assets/skins'
LIBRARIES = ('cosmetics', 'themes')
THUMBS = ROOT / 'main/images/skins'
# Review renders keep the ship centered with wide margins; crop them and shrink
# to what a Skins-tab card shows. Bundled via game.project custom_resources.
THUMB_CROP = 0.12
THUMB_SIZE = (336, 240)
HEADER = '-- Generated by tools/build_skin_index.py from assets/skins/catalog.json. Do not edit.\n'


def write(path, text):
    path.write_text(text, encoding='utf-8', newline='\n')


def lua(value):
    return json.dumps(value)  # JSON string escapes are valid Lua for these ASCII values


def factory_id(entry):
    return 'skin_factory_' + entry['id'].replace('.', '_')


def write_thumbnail(source, dest):
    from PIL import Image  # only this step needs Pillow
    with Image.open(source) as im:
        w, h = im.size
        box = (round(w * THUMB_CROP), round(h * THUMB_CROP), round(w * (1 - THUMB_CROP)), round(h * (1 - THUMB_CROP)))
        im.convert('RGB').crop(box).resize(THUMB_SIZE, Image.LANCZOS).save(dest, quality=85, optimize=True)


def write_thumbnails(entries):
    THUMBS.mkdir(parents=True, exist_ok=True)
    for old in THUMBS.glob('*.jpg'):
        old.unlink()
    for e in entries:
        write_thumbnail(ROOT / e['thumbnail'], THUMBS / f'{e["ship"]}-{e["collection"]}.jpg')
    for ship in sorted({e['ship'] for e in entries}):
        write_thumbnail(ROOT / f'artifacts/fleet/renders/{ship}-perspective.png', THUMBS / f'{ship}-default.jpg')


def main():
    collections, entries = {}, []
    for library in LIBRARIES:
        catalog = json.loads((SKINS / 'catalogs' / f'{library}.json').read_text())
        for key, c in catalog['collections'].items():
            assert key not in collections, 'Collection in two libraries: ' + key
            collections[key] = dict(name=c['name'], kind=c['kind'], description=c['description'], library=library)
        entries += [dict(e, library=library) for e in catalog['entries']]
    entries.sort(key=lambda e: e['id'])
    assert len({e['id'] for e in entries}) == len(entries), 'Duplicate skin id'

    manifest = dict(schema_version=1, scope='Asset manifest only; prices, ownership and equip state live in game data.',
                    libraries={l: f'assets/skins/catalogs/{l}.json' for l in LIBRARIES},
                    collections=collections, entries=entries)
    write(SKINS / 'catalog.json', json.dumps(manifest, indent=2) + '\n')

    hub = []
    for e in entries:
        folder = SKINS / e['ship'] / e['collection']
        assert (ROOT / e['model'].lstrip('/')).is_file(), 'Missing model: ' + e['model']
        go = '/' + (folder / 'ship.go').relative_to(ROOT).as_posix()
        write(folder / 'ship.go', f'components {{\n  id: "model"\n  component: "{e["model"]}"\n}}\n')
        hub.append(f'embedded_components {{\n  id: "{factory_id(e)}"\n  type: "factory"\n'
                   f'  data: "prototype: \\"{go}\\"\\nload_dynamically: true\\n"\n}}\n')
    write(ROOT / 'main/skin_hub.go', ''.join(hub))

    rows = [f'\t[{lua(e["id"])}] = {{ ship = {lua(e["ship"])}, collection = {lua(e["collection"])}, '
            f'chassis = {lua(e["size"] + "_" + e["role"])}, faction = {lua(e["faction"])}, '
            f'model = {lua(e["model"])}, factory = {lua(factory_id(e))} }},\n' for e in entries]
    write(ROOT / 'main/data/skins.lua',
          HEADER + '-- One entry per purchasable skin, keyed "<ship>.<collection>". `chassis` and\n'
          '-- `faction` match main/data/ships.lua\'s SHIPS key and faction_skins key;\n'
          '-- `factory` is a load_dynamically factory on main/skin_hub.go.\n\n'
          'local M = {}\n\nM.SKINS = {\n' + ''.join(rows) + '}\n\nreturn M\n')

    rows = [f'\t[{lua(k)}] = {{ name = {lua(c["name"])}, kind = {lua(c["kind"])}, description = {lua(c["description"])} }},\n'
            for k, c in collections.items()]
    write(ROOT / 'main/data/skin_collections.lua',
          HEADER + '-- Display data for each skin collection, keyed by main/data/skins.lua\'s `collection`.\n\n'
          'local M = {}\n\nM.COLLECTIONS = {\n' + ''.join(rows) + '}\n\nreturn M\n')
    write_thumbnails(entries)
    print(f'Indexed {len(entries)} skins in {len(collections)} collections')


if __name__ == '__main__':
    main()
