#!/usr/bin/env python3
"""Apply generated camera framing and current asset descriptions to Galaxy.

Does not change stats, component slots, advanced tiers, factories or ship IDs.
Run after a full build_fleet_models.py invocation. Idempotent.
"""
import json
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]


def main():
    manifest=json.loads((ROOT/'artifacts/fleet/manifest.json').read_text())
    assert manifest['roster_count']==24 and len(manifest['flight_camera'])==12
    path=ROOT/'main/outpost.gui_script'; text=path.read_text()
    lines=['local PREVIEW_CAMERA = {','\t-- Generated by tools/integrate_fleet_models.py from actual GLB bounds.',
           '\t-- Square 45-degree preview checked over a full rotation; sale cards are wider.']
    for row in manifest['ships']:
        x,y,z=row['preview']['eye_offset']; far=row['preview']['far']
        lines.append(f'\t["{row["model"]}"] = {{ eye_offset = vmath.vector3({x:.3f}, {y:.3f}, {z:.3f}), far = {far:.3f} }},')
    lines.append('}')
    text,count=re.subn(r'local PREVIEW_CAMERA = \{.*?\n\}',lambda _: '\n'.join(lines),text,count=1,flags=re.S)
    assert count==1; path.write_text(text)
    path=ROOT/'main/data/ships.lua'; text=path.read_text()
    starts=list(re.finditer(r'^\t\["((?:patrol|escort|frigate)_\w+)"\] = \{',text,re.M))
    assert len(starts)==12
    for i,match in reversed(list(enumerate(starts))):
        end=starts[i+1].start() if i+1<len(starts) else text.index('\n}\n',match.start())
        block=text[match.start():end]; chassis=match[1]
        camera=manifest['flight_camera'][chassis]
        line=f'\t\tflight_camera = {{ distance = {camera["distance"]:.3f}, height = {camera["height"]:.3f} }},'
        if re.search(r'^\t\tflight_camera =',block,re.M):
            # Retire camera comments about old model sizes, retaining actual stats.
            block=re.sub(r'(?:\t\t--[^\n]*\n)+(?=\t\tflight_camera =)', '',block)
            block=re.sub(r'^\t\tflight_camera = [^\n]+',line,block,flags=re.M)
        else:
            block=re.sub(r'(^\t\tclass = [^\n]+)',lambda m:m[0]+'\n'+line,block,count=1,flags=re.M)
        skins=[r for r in manifest['ships'] if r['class']+'_'+r['role']==chassis]
        lines=['\t\tfaction_skins = {','\t\t\t-- Original species hulls; tools/build_fleet_models.py. Sardine retains its approved asset.',
               '\t\t\t-- One mesh/texture each; meters, +Z forward. Hardware conveys role, not slot counts.']
        for row in skins:
            lines.append('\t\t\t-- '+row['name']+': '+row['identity']+'.')
            lines.append(f'\t\t\t{row["faction"]} = {{ name = "{row["name"]}", model = "{row["model"]}", weapon_gui = "<TBD>" }},')
        lines.append('\t\t},')
        block,count=re.subn(r'\t\tfaction_skins = \{.*?\n\t\t\},',lambda _:'\n'.join(lines),block,count=1,flags=re.S)
        assert count==1,chassis
        text=text[:match.start()]+block+text[end:]
    path.write_text(text)
    print('Integrated 24 hangar cameras and 12 flight cameras; gameplay tables preserved.')


if __name__=='__main__': main()
