#!/usr/bin/env python3
"""Copy the game rules the server enforces into the Nakama modules folder.

nakama-server/modules/economy.lua runs the client's own main/session.lua (and
the data it requires) to apply and check every change to a player's profile,
so the rules are written once. Nakama can only load files from its modules
folder, so this copies them to nakama-server/modules/<same path>, keeping the
client's require() names working unchanged.

Run after editing any of the files below, then restart Nakama:
    python tools/sync_server_rules.py
Check that the copies are current (e.g. before deploying):
    python tools/sync_server_rules.py --check
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES = ROOT / 'nakama-server/modules'
SOURCES = [
    'main/version.lua',
    'main/session.lua',
    'main/data/ships.lua',
    'main/data/star_systems.lua',
    'main/data/skins.lua',
    'main/data/skin_prices.lua',
    *sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / 'main/data/modules').glob('*.lua')),
]
HEADER = '-- GENERATED by tools/sync_server_rules.py from {src} - edit that file, not this copy.\n'


def expected(src):
    return HEADER.format(src=src) + (ROOT / src).read_text(encoding='utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='fail if any copy is missing or out of date')
    args = parser.parse_args()

    stale = []
    for src in SOURCES:
        dest = MODULES / src
        text = expected(src)
        if dest.exists() and dest.read_text(encoding='utf-8') == text:
            continue
        if args.check:
            stale.append(src)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(text, encoding='utf-8', newline='\n')
            print('copied', src)

    # Copies whose source was removed.
    wanted = {MODULES / src for src in SOURCES}
    for dest in (MODULES / 'main').rglob('*.lua'):
        if dest not in wanted:
            if args.check:
                stale.append(dest.relative_to(MODULES).as_posix() + ' (no longer synced)')
            else:
                dest.unlink()
                print('removed', dest.relative_to(ROOT))

    if args.check and stale:
        print('Server rules are out of date; run python tools/sync_server_rules.py:\n  ' + '\n  '.join(stale))
        sys.exit(1)
    if args.check:
        print(f'Server rules up to date ({len(SOURCES)} files).')


if __name__ == '__main__':
    main()
