-- Weapon (Auto Cannon) module entries (plan.md §2.8). Two concrete entries
-- now exist: the basic Ordinance-type cannon and the Mining Cannon every
-- new character is gifted one of each of, along with the Patrol 1 ship
-- (§2.1.2), per direct instruction. Stat fields (power_draw/cooldown/
-- wear_per_use/damage, the shared schema from §2.8) are not yet
-- specified, so they're omitted entirely rather than guessed, per
-- §0/§4's "don't invent unconfirmed numbers" rule.
--
-- Naming convention (decided): combat (Ordinance-type) auto cannons are
-- named after INSECTS, sized to match the ship class they're built for —
-- same "real-world animal sized to the ship class" pattern as the ship
-- roster's fish (Accord)/bird (Swarm) names (§2.1.2), just a third animal
-- family reserved for this one weapon subtype. Scale, smallest ship class
-- to largest (only the Patrol-tier entry actually exists yet; the rest
-- are reserved for whenever an Escort/Frigate/Carrier-specific cannon is
-- added, §2.1):
--   Patrol  -> Gnat     (this file's "auto_cannon_basic")
--   Escort  -> Hornet
--   Frigate -> Locust
--   Carrier -> Beetle
--
-- Mining-type cannons are NOT part of the insect scheme - they get their
-- own class-sized naming scale instead, using mining/prospecting
-- terminology (decided). Unlike the combat scale above, all four tiers
-- are now implemented (item keys below):
--   Patrol  -> Digger      ("mining_cannon_basic")
--   Escort  -> Miner       ("mining_cannon_escort")
--   Frigate -> Speculator  ("mining_cannon_frigate")
--   Carrier -> Prospector  ("mining_cannon_carrier" - the name the
--                           Patrol-tier entry used before being renamed
--                           to Digger, reused here rather than retired)
--
-- `ship_class` (decided, singular - a plain string, not a list): each
-- cannon belongs to exactly ONE ship class, not "fits anywhere" -
-- matching the naming scale above (a Gnat is a Patrol-sized weapon, not
-- a generic one that happens to be named after a small insect). NOTE:
-- this field isn't actually enforced anywhere yet (no fitting-screen or
-- install-time check reads it) - it's data awaiting that logic, not a
-- currently-active restriction (plan.md §4). This now matters more than
-- it did with just Gnat/Digger (both Patrol, so the missing check was
-- moot in practice): Miner/Speculator/Prospector are Escort/Frigate/
-- Carrier-only, but with no ships in those classes yet AND no
-- enforcement, they're currently draggable onto the Patrol ship anyway.
--
-- `icon`: the region name (image filename, no extension) within
-- main/images/icons.atlas — generated by tools/build_module_icons.py,
-- shown on the outpost screen's ship visual slot markers instead of the
-- item's name text (plan.md §4/§2.8's fitting-screen notes). Miner/
-- Speculator/Prospector all placeholder-share Digger's icon for now -
-- distinct per-tier mining-cannon art hasn't been designed (plan.md §4).

local M = {}

M.AUTOCANNONS = {
	["auto_cannon_basic"] = {
		name = "Gnat", -- Patrol-tier combat auto cannon, see the naming-scale comment above
		type = "weapon",
		subtype = "auto_cannon",
		cannon_type = "ordinance", -- consumes ordinance, combat-capable (§2.8)
		behavior = "toggle", -- §2.8: weapons are always toggle-type
		ship_class = "Patrol", -- see the ship_class comment above
		icon = "auto_cannon_basic",
	},
	["mining_cannon_basic"] = {
		name = "Digger", -- Patrol-tier mining cannon, see the mining naming-scale comment above
		type = "weapon",
		subtype = "auto_cannon",
		cannon_type = "mining", -- no ordinance needed, mining-focused, weak vs. ships (§2.8)
		behavior = "toggle", -- §2.8: weapons are always toggle-type
		ship_class = "Patrol", -- see the ship_class comment above
		icon = "mining_cannon_basic",
	},
	["mining_cannon_escort"] = {
		name = "Miner", -- Escort-tier mining cannon, see the mining naming-scale comment above
		type = "weapon",
		subtype = "auto_cannon",
		cannon_type = "mining",
		behavior = "toggle", -- §2.8: weapons are always toggle-type
		ship_class = "Escort", -- see the ship_class comment above - NOT YET enforced (plan.md §4)
		icon = "mining_cannon_basic", -- placeholder - shares Digger's icon, see the icon comment above
	},
	["mining_cannon_frigate"] = {
		name = "Speculator", -- Frigate-tier mining cannon, see the mining naming-scale comment above
		type = "weapon",
		subtype = "auto_cannon",
		cannon_type = "mining",
		behavior = "toggle", -- §2.8: weapons are always toggle-type
		ship_class = "Frigate", -- see the ship_class comment above - NOT YET enforced (plan.md §4)
		icon = "mining_cannon_basic", -- placeholder - shares Digger's icon, see the icon comment above
	},
	["mining_cannon_carrier"] = {
		name = "Prospector", -- Carrier-tier mining cannon, see the mining naming-scale comment above
		type = "weapon",
		subtype = "auto_cannon",
		cannon_type = "mining",
		behavior = "toggle", -- §2.8: weapons are always toggle-type
		ship_class = "Carrier", -- see the ship_class comment above - NOT YET enforced (plan.md §4)
		icon = "mining_cannon_basic", -- placeholder - shares Digger's icon, see the icon comment above
	},
}

return M
